/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetMarketingTagCollection200, GetMarketingTagCollectionParams } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of MarketingTag resources.
 */
export const getMarketingTagCollection = (
  params?: GetMarketingTagCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetMarketingTagCollection200>(
    { url: `/api/v2/shop/marketing-tags`, method: "get", params, signal },
    options,
  );
};

export const getGetMarketingTagCollectionQueryKey = (params?: GetMarketingTagCollectionParams) => {
  return [`/api/v2/shop/marketing-tags`, ...(params ? [params] : [])] as const;
};

export const getGetMarketingTagCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketingTagCollection>>,
  TError = unknown,
>(
  params?: GetMarketingTagCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getMarketingTagCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMarketingTagCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketingTagCollection>>> = ({
    signal,
  }) => getMarketingTagCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketingTagCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketingTagCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketingTagCollection>>
>;
export type GetMarketingTagCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of MarketingTag resources.
 */
export const useGetMarketingTagCollection = <
  TData = Awaited<ReturnType<typeof getMarketingTagCollection>>,
  TError = unknown,
>(
  params?: GetMarketingTagCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getMarketingTagCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMarketingTagCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a MarketingTag resource.
 */
export const getMarketingTagItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/marketing-tags/${id}`, method: "get", signal },
    options,
  );
};

export const getGetMarketingTagItemQueryKey = (id: string) => {
  return [`/api/v2/shop/marketing-tags/${id}`] as const;
};

export const getGetMarketingTagItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketingTagItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getMarketingTagItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMarketingTagItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketingTagItem>>> = ({ signal }) =>
    getMarketingTagItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketingTagItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketingTagItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketingTagItem>>
>;
export type GetMarketingTagItemQueryError = unknown;

/**
 * @summary Retrieves a MarketingTag resource.
 */
export const useGetMarketingTagItem = <
  TData = Awaited<ReturnType<typeof getMarketingTagItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getMarketingTagItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMarketingTagItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
