/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AdminGetCountryCollection200,
  AdminGetCountryCollectionParams,
  ApiCountriesProvincesGetSubresource200,
  ApiCountriesProvincesGetSubresourceParams,
  CountryJsonld,
  CountryJsonldAdminCountryCreate,
  CountryJsonldAdminCountryRead,
  CountryJsonldAdminCountryUpdate,
  CountryJsonldShopCountryRead,
  CountryShopCountryRead,
  ShopGetCountryCollectionParams,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of Country resources.
 */
export const adminGetCountryCollection = (
  params?: AdminGetCountryCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AdminGetCountryCollection200>(
    { url: `/api/v2/admin/countries`, method: "get", params, signal },
    options,
  );
};

export const getAdminGetCountryCollectionQueryKey = (params?: AdminGetCountryCollectionParams) => {
  return [`/api/v2/admin/countries`, ...(params ? [params] : [])] as const;
};

export const getAdminGetCountryCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetCountryCollection>>,
  TError = unknown,
>(
  params?: AdminGetCountryCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof adminGetCountryCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetCountryCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetCountryCollection>>> = ({
    signal,
  }) => adminGetCountryCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetCountryCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetCountryCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetCountryCollection>>
>;
export type AdminGetCountryCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of Country resources.
 */
export const useAdminGetCountryCollection = <
  TData = Awaited<ReturnType<typeof adminGetCountryCollection>>,
  TError = unknown,
>(
  params?: AdminGetCountryCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof adminGetCountryCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetCountryCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Creates a Country resource.
 */
export const adminPostCountryCollection = (
  countryJsonldAdminCountryCreate: NonReadonly<CountryJsonldAdminCountryCreate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<CountryJsonld>(
    {
      url: `/api/v2/admin/countries`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: countryJsonldAdminCountryCreate,
    },
    options,
  );
};

export const getAdminPostCountryCollectionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPostCountryCollection>>,
    TError,
    { data: NonReadonly<CountryJsonldAdminCountryCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminPostCountryCollection>>,
  TError,
  { data: NonReadonly<CountryJsonldAdminCountryCreate> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminPostCountryCollection>>,
    { data: NonReadonly<CountryJsonldAdminCountryCreate> }
  > = props => {
    const { data } = props ?? {};

    return adminPostCountryCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminPostCountryCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminPostCountryCollection>>
>;
export type AdminPostCountryCollectionMutationBody = NonReadonly<CountryJsonldAdminCountryCreate>;
export type AdminPostCountryCollectionMutationError = void;

/**
 * @summary Creates a Country resource.
 */
export const useAdminPostCountryCollection = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPostCountryCollection>>,
    TError,
    { data: NonReadonly<CountryJsonldAdminCountryCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getAdminPostCountryCollectionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Retrieves a Country resource.
 */
export const adminGetCountryItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CountryJsonldAdminCountryRead>(
    { url: `/api/v2/admin/countries/${code}`, method: "get", signal },
    options,
  );
};

export const getAdminGetCountryItemQueryKey = (code: string) => {
  return [`/api/v2/admin/countries/${code}`] as const;
};

export const getAdminGetCountryItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetCountryItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof adminGetCountryItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetCountryItemQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetCountryItem>>> = ({ signal }) =>
    adminGetCountryItem(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetCountryItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetCountryItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetCountryItem>>
>;
export type AdminGetCountryItemQueryError = void;

/**
 * @summary Retrieves a Country resource.
 */
export const useAdminGetCountryItem = <
  TData = Awaited<ReturnType<typeof adminGetCountryItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof adminGetCountryItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetCountryItemQueryOptions(code, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Replaces the Country resource.
 */
export const adminPutCountryItem = (
  code: string,
  countryJsonldAdminCountryUpdate: NonReadonly<CountryJsonldAdminCountryUpdate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<CountryJsonld>(
    {
      url: `/api/v2/admin/countries/${code}`,
      method: "put",
      headers: { "Content-Type": "application/ld+json" },
      data: countryJsonldAdminCountryUpdate,
    },
    options,
  );
};

export const getAdminPutCountryItemMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPutCountryItem>>,
    TError,
    { code: string; data: NonReadonly<CountryJsonldAdminCountryUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminPutCountryItem>>,
  TError,
  { code: string; data: NonReadonly<CountryJsonldAdminCountryUpdate> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminPutCountryItem>>,
    { code: string; data: NonReadonly<CountryJsonldAdminCountryUpdate> }
  > = props => {
    const { code, data } = props ?? {};

    return adminPutCountryItem(code, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminPutCountryItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminPutCountryItem>>
>;
export type AdminPutCountryItemMutationBody = NonReadonly<CountryJsonldAdminCountryUpdate>;
export type AdminPutCountryItemMutationError = void;

/**
 * @summary Replaces the Country resource.
 */
export const useAdminPutCountryItem = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPutCountryItem>>,
    TError,
    { code: string; data: NonReadonly<CountryJsonldAdminCountryUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getAdminPutCountryItemMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Retrieves the collection of Province resources.
 */
export const apiCountriesProvincesGetSubresource = (
  code: string,
  params?: ApiCountriesProvincesGetSubresourceParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApiCountriesProvincesGetSubresource200>(
    { url: `/api/v2/admin/countries/${code}/provinces`, method: "get", params, signal },
    options,
  );
};

export const getApiCountriesProvincesGetSubresourceQueryKey = (
  code: string,
  params?: ApiCountriesProvincesGetSubresourceParams,
) => {
  return [`/api/v2/admin/countries/${code}/provinces`, ...(params ? [params] : [])] as const;
};

export const getApiCountriesProvincesGetSubresourceQueryOptions = <
  TData = Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>,
  TError = void,
>(
  code: string,
  params?: ApiCountriesProvincesGetSubresourceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiCountriesProvincesGetSubresourceQueryKey(code, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>> = ({
    signal,
  }) => apiCountriesProvincesGetSubresource(code, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiCountriesProvincesGetSubresourceQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>
>;
export type ApiCountriesProvincesGetSubresourceQueryError = void;

/**
 * @summary Retrieves the collection of Province resources.
 */
export const useApiCountriesProvincesGetSubresource = <
  TData = Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>,
  TError = void,
>(
  code: string,
  params?: ApiCountriesProvincesGetSubresourceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof apiCountriesProvincesGetSubresource>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getApiCountriesProvincesGetSubresourceQueryOptions(code, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves the collection of Country resources.
 */
export const shopGetCountryCollection = (
  params?: ShopGetCountryCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CountryShopCountryRead[]>(
    { url: `/api/v2/shop/countries`, method: "get", params, signal },
    options,
  );
};

export const getShopGetCountryCollectionQueryKey = (params?: ShopGetCountryCollectionParams) => {
  return [`/api/v2/shop/countries`, ...(params ? [params] : [])] as const;
};

export const getShopGetCountryCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetCountryCollection>>,
  TError = unknown,
>(
  params?: ShopGetCountryCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetCountryCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetCountryCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetCountryCollection>>> = ({
    signal,
  }) => shopGetCountryCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetCountryCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetCountryCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetCountryCollection>>
>;
export type ShopGetCountryCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of Country resources.
 */
export const useShopGetCountryCollection = <
  TData = Awaited<ReturnType<typeof shopGetCountryCollection>>,
  TError = unknown,
>(
  params?: ShopGetCountryCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetCountryCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetCountryCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a Country resource.
 */
export const shopGetCountryItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CountryJsonldShopCountryRead>(
    { url: `/api/v2/shop/countries/${code}`, method: "get", signal },
    options,
  );
};

export const getShopGetCountryItemQueryKey = (code: string) => {
  return [`/api/v2/shop/countries/${code}`] as const;
};

export const getShopGetCountryItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetCountryItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetCountryItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetCountryItemQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetCountryItem>>> = ({ signal }) =>
    shopGetCountryItem(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetCountryItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetCountryItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetCountryItem>>
>;
export type ShopGetCountryItemQueryError = void;

/**
 * @summary Retrieves a Country resource.
 */
export const useShopGetCountryItem = <
  TData = Awaited<ReturnType<typeof shopGetCountryItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetCountryItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetCountryItemQueryOptions(code, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
