/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductOptionTranslationJsonld } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductOptionTranslation resource.
 */
export const adminGetProductOptionTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductOptionTranslationJsonld>(
    { url: `/api/v2/admin/product-option-translations/${id}`, method: "get", signal },
    options,
  );
};

export const getAdminGetProductOptionTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/admin/product-option-translations/${id}`] as const;
};

export const getAdminGetProductOptionTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetProductOptionTranslationItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>
  > = ({ signal }) => adminGetProductOptionTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetProductOptionTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>
>;
export type AdminGetProductOptionTranslationItemQueryError = void;

/**
 * @summary Retrieves a ProductOptionTranslation resource.
 */
export const useAdminGetProductOptionTranslationItem = <
  TData = Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductOptionTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetProductOptionTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
