/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { DirectSaleItemDTOJsonldShopDirectSaleItemDtoRead } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a DirectSaleItemDTO resource.
 */
export const getDirectSaleItemDTOItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DirectSaleItemDTOJsonldShopDirectSaleItemDtoRead>(
    { url: `/api/v2/shop/direct-sale-items/${code}`, method: "get", signal },
    options,
  );
};

export const getGetDirectSaleItemDTOItemQueryKey = (code: string) => {
  return [`/api/v2/shop/direct-sale-items/${code}`] as const;
};

export const getGetDirectSaleItemDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDirectSaleItemDTOItemQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>> = ({
    signal,
  }) => getDirectSaleItemDTOItem(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDirectSaleItemDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>
>;
export type GetDirectSaleItemDTOItemQueryError = void;

/**
 * @summary Retrieves a DirectSaleItemDTO resource.
 */
export const useGetDirectSaleItemDTOItem = <
  TData = Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getDirectSaleItemDTOItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetDirectSaleItemDTOItemQueryOptions(code, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
