/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetProductVariantProductVariantSaleDTOCollection200,
  GetProductVariantProductVariantSaleDTOCollectionParams,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of ProductVariantSaleDTO resources.
 */
export const getProductVariantProductVariantSaleDTOCollection = (
  params?: GetProductVariantProductVariantSaleDTOCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetProductVariantProductVariantSaleDTOCollection200>(
    { url: `/api/v2/shop/product-variant-sale`, method: "get", params, signal },
    options,
  );
};

export const getGetProductVariantProductVariantSaleDTOCollectionQueryKey = (
  params?: GetProductVariantProductVariantSaleDTOCollectionParams,
) => {
  return [`/api/v2/shop/product-variant-sale`, ...(params ? [params] : [])] as const;
};

export const getGetProductVariantProductVariantSaleDTOCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>,
  TError = unknown,
>(
  params?: GetProductVariantProductVariantSaleDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProductVariantProductVariantSaleDTOCollectionQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>
  > = ({ signal }) =>
    getProductVariantProductVariantSaleDTOCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProductVariantProductVariantSaleDTOCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>
>;
export type GetProductVariantProductVariantSaleDTOCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of ProductVariantSaleDTO resources.
 */
export const useGetProductVariantProductVariantSaleDTOCollection = <
  TData = Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>,
  TError = unknown,
>(
  params?: GetProductVariantProductVariantSaleDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProductVariantProductVariantSaleDTOCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProductVariantProductVariantSaleDTOCollectionQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a ProductVariantSaleDTO resource.
 */
export const getProductVariantSaleDTOItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/product-variant-sale-d-t-os/${id}`, method: "get", signal },
    options,
  );
};

export const getGetProductVariantSaleDTOItemQueryKey = (id: string) => {
  return [`/api/v2/shop/product-variant-sale-d-t-os/${id}`] as const;
};

export const getGetProductVariantSaleDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductVariantSaleDTOItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>> = ({
    signal,
  }) => getProductVariantSaleDTOItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProductVariantSaleDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>
>;
export type GetProductVariantSaleDTOItemQueryError = unknown;

/**
 * @summary Retrieves a ProductVariantSaleDTO resource.
 */
export const useGetProductVariantSaleDTOItem = <
  TData = Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProductVariantSaleDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProductVariantSaleDTOItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
