/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { CustomsFeeRateShopCustomsFeeRateRead } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of CustomsFeeRate resources.
 */
export const getCustomsFeeRateCollection = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CustomsFeeRateShopCustomsFeeRateRead[]>(
    { url: `/api/v2/shop/customs-fee-rates`, method: "get", signal },
    options,
  );
};

export const getGetCustomsFeeRateCollectionQueryKey = () => {
  return [`/api/v2/shop/customs-fee-rates`] as const;
};

export const getGetCustomsFeeRateCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getCustomsFeeRateCollection>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getCustomsFeeRateCollection>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCustomsFeeRateCollectionQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomsFeeRateCollection>>> = ({
    signal,
  }) => getCustomsFeeRateCollection(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCustomsFeeRateCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCustomsFeeRateCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCustomsFeeRateCollection>>
>;
export type GetCustomsFeeRateCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of CustomsFeeRate resources.
 */
export const useGetCustomsFeeRateCollection = <
  TData = Awaited<ReturnType<typeof getCustomsFeeRateCollection>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getCustomsFeeRateCollection>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCustomsFeeRateCollectionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a CustomsFeeRate resource.
 */
export const getCustomsFeeRateItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/customs-fee-rates/${id}`, method: "get", signal },
    options,
  );
};

export const getGetCustomsFeeRateItemQueryKey = (id: string) => {
  return [`/api/v2/shop/customs-fee-rates/${id}`] as const;
};

export const getGetCustomsFeeRateItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getCustomsFeeRateItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getCustomsFeeRateItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCustomsFeeRateItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomsFeeRateItem>>> = ({ signal }) =>
    getCustomsFeeRateItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCustomsFeeRateItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCustomsFeeRateItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCustomsFeeRateItem>>
>;
export type GetCustomsFeeRateItemQueryError = unknown;

/**
 * @summary Retrieves a CustomsFeeRate resource.
 */
export const useGetCustomsFeeRateItem = <
  TData = Awaited<ReturnType<typeof getCustomsFeeRateItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getCustomsFeeRateItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCustomsFeeRateItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
