/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetHealthCheckDTOCollection200,
  GetHealthCheckDTOCollectionParams,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of HealthCheckDTO resources.
 */
export const getHealthCheckDTOCollection = (
  params?: GetHealthCheckDTOCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetHealthCheckDTOCollection200>(
    { url: `/api/v2/health-check`, method: "get", params, signal },
    options,
  );
};

export const getGetHealthCheckDTOCollectionQueryKey = (
  params?: GetHealthCheckDTOCollectionParams,
) => {
  return [`/api/v2/health-check`, ...(params ? [params] : [])] as const;
};

export const getGetHealthCheckDTOCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealthCheckDTOCollection>>,
  TError = unknown,
>(
  params?: GetHealthCheckDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckDTOCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthCheckDTOCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthCheckDTOCollection>>> = ({
    signal,
  }) => getHealthCheckDTOCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHealthCheckDTOCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHealthCheckDTOCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealthCheckDTOCollection>>
>;
export type GetHealthCheckDTOCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of HealthCheckDTO resources.
 */
export const useGetHealthCheckDTOCollection = <
  TData = Awaited<ReturnType<typeof getHealthCheckDTOCollection>>,
  TError = unknown,
>(
  params?: GetHealthCheckDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getHealthCheckDTOCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetHealthCheckDTOCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
