// Code generated by Slice Machine. DO NOT EDIT.

import AuctionReport from "./AuctionReport";
import BannerAllOurWinesDesktop from "./BannerAllOurWinesDesktop";
import CardDuo from "./CardDuo";
import CgsItem from "./CgsItem";
import GroupedThreeBlocksBanner from "./GroupedThreeBlocksBanner";
import HeroBlock from "./HeroBlock";
import Indices from "./Indices";
import Journal from "./Journal";
import LastOrders from "./LastOrders";
import NewReleases from "./NewReleases";
import RatingsSearch from "./RatingsSearch";
import ReinsuranceBanner from "./ReinsuranceBanner";
import SellMyWines from "./SellMyWines";
import SliderHome from "./SliderHome";
import StandardBanner from "./StandardBanner";
import ThreeBlocksBanner from "./ThreeBlocksBanner";
import WelcomeBlock from "./WelcomeBlock";

export {
  AuctionReport,
  BannerAllOurWinesDesktop,
  CardDuo,
  CgsItem,
  GroupedThreeBlocksBanner,
  HeroBlock,
  Indices,
  Journal,
  LastOrders,
  NewReleases,
  RatingsSearch,
  ReinsuranceBanner,
  SellMyWines,
  SliderHome,
  StandardBanner,
  ThreeBlocksBanner,
  WelcomeBlock,
};

export const components = {
  auction_report: AuctionReport,
  banner_all_our_wines_desktop: BannerAllOurWinesDesktop,
  offer: CardDuo,
  cgs_item: CgsItem,
  grouped_three_block_banner: GroupedThreeBlocksBanner,
  hero_block: HeroBlock,
  indices: Indices,
  journal: Journal,
  last_orders: LastOrders,
  new_releases: NewReleases,
  ratings_search: RatingsSearch,
  reinsurance_banner: ReinsuranceBanner,
  sell_my_wines: SellMyWines,
  slider_home: SliderHome,
  banner: StandardBanner,
  three_blocks_banner: ThreeBlocksBanner,
  welcome_block: WelcomeBlock,
};
