/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation } from "@tanstack/react-query";
import type { MutationFunction, UseMutationOptions } from "@tanstack/react-query";
import type { RequestContactJsonldShopContactRequestCreate } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Send contact request
 */
export const shopSendContactRequestRequestContactCollection = (
  requestContactJsonldShopContactRequestCreate: NonReadonly<RequestContactJsonldShopContactRequestCreate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/api/v2/shop/contact-requests`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: requestContactJsonldShopContactRequestCreate,
    },
    options,
  );
};

export const getShopSendContactRequestRequestContactCollectionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shopSendContactRequestRequestContactCollection>>,
    TError,
    { data: NonReadonly<RequestContactJsonldShopContactRequestCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shopSendContactRequestRequestContactCollection>>,
  TError,
  { data: NonReadonly<RequestContactJsonldShopContactRequestCreate> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shopSendContactRequestRequestContactCollection>>,
    { data: NonReadonly<RequestContactJsonldShopContactRequestCreate> }
  > = props => {
    const { data } = props ?? {};

    return shopSendContactRequestRequestContactCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShopSendContactRequestRequestContactCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof shopSendContactRequestRequestContactCollection>>
>;
export type ShopSendContactRequestRequestContactCollectionMutationBody =
  NonReadonly<RequestContactJsonldShopContactRequestCreate>;
export type ShopSendContactRequestRequestContactCollectionMutationError = unknown;

/**
 * @summary Send contact request
 */
export const useShopSendContactRequestRequestContactCollection = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shopSendContactRequestRequestContactCollection>>,
    TError,
    { data: NonReadonly<RequestContactJsonldShopContactRequestCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getShopSendContactRequestRequestContactCollectionMutationOptions(options);

  return useMutation(mutationOptions);
};
