/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AdminGetShippingCategoryCollection200,
  AdminGetShippingCategoryCollectionParams,
  ShippingCategoryJsonld,
  ShippingCategoryJsonldAdminShippingCategoryCreate,
  ShippingCategoryJsonldAdminShippingCategoryRead,
  ShippingCategoryJsonldAdminShippingCategoryUpdate,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of ShippingCategory resources.
 */
export const adminGetShippingCategoryCollection = (
  params?: AdminGetShippingCategoryCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AdminGetShippingCategoryCollection200>(
    { url: `/api/v2/admin/shipping-categories`, method: "get", params, signal },
    options,
  );
};

export const getAdminGetShippingCategoryCollectionQueryKey = (
  params?: AdminGetShippingCategoryCollectionParams,
) => {
  return [`/api/v2/admin/shipping-categories`, ...(params ? [params] : [])] as const;
};

export const getAdminGetShippingCategoryCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>,
  TError = unknown,
>(
  params?: AdminGetShippingCategoryCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetShippingCategoryCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>> = ({
    signal,
  }) => adminGetShippingCategoryCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetShippingCategoryCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>
>;
export type AdminGetShippingCategoryCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of ShippingCategory resources.
 */
export const useAdminGetShippingCategoryCollection = <
  TData = Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>,
  TError = unknown,
>(
  params?: AdminGetShippingCategoryCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetShippingCategoryCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetShippingCategoryCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Creates a ShippingCategory resource.
 */
export const adminPostShippingCategoryCollection = (
  shippingCategoryJsonldAdminShippingCategoryCreate: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryCreate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ShippingCategoryJsonld>(
    {
      url: `/api/v2/admin/shipping-categories`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: shippingCategoryJsonldAdminShippingCategoryCreate,
    },
    options,
  );
};

export const getAdminPostShippingCategoryCollectionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPostShippingCategoryCollection>>,
    TError,
    { data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminPostShippingCategoryCollection>>,
  TError,
  { data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryCreate> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminPostShippingCategoryCollection>>,
    { data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryCreate> }
  > = props => {
    const { data } = props ?? {};

    return adminPostShippingCategoryCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminPostShippingCategoryCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminPostShippingCategoryCollection>>
>;
export type AdminPostShippingCategoryCollectionMutationBody =
  NonReadonly<ShippingCategoryJsonldAdminShippingCategoryCreate>;
export type AdminPostShippingCategoryCollectionMutationError = void;

/**
 * @summary Creates a ShippingCategory resource.
 */
export const useAdminPostShippingCategoryCollection = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPostShippingCategoryCollection>>,
    TError,
    { data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryCreate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getAdminPostShippingCategoryCollectionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Retrieves a ShippingCategory resource.
 */
export const adminGetShippingCategoryItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ShippingCategoryJsonldAdminShippingCategoryRead>(
    { url: `/api/v2/admin/shipping-categories/${code}`, method: "get", signal },
    options,
  );
};

export const getAdminGetShippingCategoryItemQueryKey = (code: string) => {
  return [`/api/v2/admin/shipping-categories/${code}`] as const;
};

export const getAdminGetShippingCategoryItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetShippingCategoryItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetShippingCategoryItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetShippingCategoryItemQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetShippingCategoryItem>>> = ({
    signal,
  }) => adminGetShippingCategoryItem(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetShippingCategoryItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetShippingCategoryItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetShippingCategoryItem>>
>;
export type AdminGetShippingCategoryItemQueryError = void;

/**
 * @summary Retrieves a ShippingCategory resource.
 */
export const useAdminGetShippingCategoryItem = <
  TData = Awaited<ReturnType<typeof adminGetShippingCategoryItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetShippingCategoryItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetShippingCategoryItemQueryOptions(code, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Replaces the ShippingCategory resource.
 */
export const adminPutShippingCategoryItem = (
  code: string,
  shippingCategoryJsonldAdminShippingCategoryUpdate: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryUpdate>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ShippingCategoryJsonld>(
    {
      url: `/api/v2/admin/shipping-categories/${code}`,
      method: "put",
      headers: { "Content-Type": "application/ld+json" },
      data: shippingCategoryJsonldAdminShippingCategoryUpdate,
    },
    options,
  );
};

export const getAdminPutShippingCategoryItemMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPutShippingCategoryItem>>,
    TError,
    { code: string; data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminPutShippingCategoryItem>>,
  TError,
  { code: string; data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryUpdate> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminPutShippingCategoryItem>>,
    { code: string; data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryUpdate> }
  > = props => {
    const { code, data } = props ?? {};

    return adminPutShippingCategoryItem(code, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminPutShippingCategoryItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminPutShippingCategoryItem>>
>;
export type AdminPutShippingCategoryItemMutationBody =
  NonReadonly<ShippingCategoryJsonldAdminShippingCategoryUpdate>;
export type AdminPutShippingCategoryItemMutationError = void;

/**
 * @summary Replaces the ShippingCategory resource.
 */
export const useAdminPutShippingCategoryItem = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminPutShippingCategoryItem>>,
    TError,
    { code: string; data: NonReadonly<ShippingCategoryJsonldAdminShippingCategoryUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getAdminPutShippingCategoryItemMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Removes the ShippingCategory resource.
 */
export const adminDeleteShippingCategoryItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/v2/admin/shipping-categories/${code}`, method: "delete" },
    options,
  );
};

export const getAdminDeleteShippingCategoryItemMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminDeleteShippingCategoryItem>>,
    TError,
    { code: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminDeleteShippingCategoryItem>>,
  TError,
  { code: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminDeleteShippingCategoryItem>>,
    { code: string }
  > = props => {
    const { code } = props ?? {};

    return adminDeleteShippingCategoryItem(code, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminDeleteShippingCategoryItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminDeleteShippingCategoryItem>>
>;

export type AdminDeleteShippingCategoryItemMutationError = unknown;

/**
 * @summary Removes the ShippingCategory resource.
 */
export const useAdminDeleteShippingCategoryItem = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminDeleteShippingCategoryItem>>,
    TError,
    { code: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getAdminDeleteShippingCategoryItemMutationOptions(options);

  return useMutation(mutationOptions);
};
