/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AuctionItemDTOAuctionBidDTOJsonld,
  AuctionItemDTOAuctionBidResultDTOShopAuctionItemDtoRead,
  AuctionItemDTOJsonldShopAuctionItemDtoRead,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a AuctionItemDTO resource.
 */
export const getAuctionItemDTOItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuctionItemDTOJsonldShopAuctionItemDtoRead>(
    { url: `/api/v2/shop/auction-items/${code}`, method: "get", signal },
    options,
  );
};

export const getGetAuctionItemDTOItemQueryKey = (code: string) => {
  return [`/api/v2/shop/auction-items/${code}`] as const;
};

export const getGetAuctionItemDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuctionItemDTOItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionItemDTOItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuctionItemDTOItemQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuctionItemDTOItem>>> = ({ signal }) =>
    getAuctionItemDTOItem(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuctionItemDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuctionItemDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuctionItemDTOItem>>
>;
export type GetAuctionItemDTOItemQueryError = void;

/**
 * @summary Retrieves a AuctionItemDTO resource.
 */
export const useGetAuctionItemDTOItem = <
  TData = Awaited<ReturnType<typeof getAuctionItemDTOItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionItemDTOItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuctionItemDTOItemQueryOptions(code, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Creates a AuctionItemDTO resource.
 */
export const postAuctionItemDTOItem = (
  code: string,
  auctionItemDTOAuctionBidDTOJsonld: NonReadonly<AuctionItemDTOAuctionBidDTOJsonld>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuctionItemDTOAuctionBidResultDTOShopAuctionItemDtoRead>(
    {
      url: `/api/v2/shop/auction-items/${code}/bid`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: auctionItemDTOAuctionBidDTOJsonld,
    },
    options,
  );
};

export const getPostAuctionItemDTOItemMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuctionItemDTOItem>>,
    TError,
    { code: string; data: NonReadonly<AuctionItemDTOAuctionBidDTOJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuctionItemDTOItem>>,
  TError,
  { code: string; data: NonReadonly<AuctionItemDTOAuctionBidDTOJsonld> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuctionItemDTOItem>>,
    { code: string; data: NonReadonly<AuctionItemDTOAuctionBidDTOJsonld> }
  > = props => {
    const { code, data } = props ?? {};

    return postAuctionItemDTOItem(code, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuctionItemDTOItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuctionItemDTOItem>>
>;
export type PostAuctionItemDTOItemMutationBody = NonReadonly<AuctionItemDTOAuctionBidDTOJsonld>;
export type PostAuctionItemDTOItemMutationError = void;

/**
 * @summary Creates a AuctionItemDTO resource.
 */
export const usePostAuctionItemDTOItem = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuctionItemDTOItem>>,
    TError,
    { code: string; data: NonReadonly<AuctionItemDTOAuctionBidDTOJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getPostAuctionItemDTOItemMutationOptions(options);

  return useMutation(mutationOptions);
};
