/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetTotalProductVariantSaleDTOCollection200,
  GetTotalProductVariantSaleDTOCollectionParams,
  GetTotalProductVariantSaleDTOItemParams,
  TotalProductVariantSaleDTOJsonld,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of TotalProductVariantSaleDTO resources.
 */
export const getTotalProductVariantSaleDTOCollection = (
  params?: GetTotalProductVariantSaleDTOCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTotalProductVariantSaleDTOCollection200>(
    { url: `/api/v2/shop/total-product-variant-sales`, method: "get", params, signal },
    options,
  );
};

export const getGetTotalProductVariantSaleDTOCollectionQueryKey = (
  params?: GetTotalProductVariantSaleDTOCollectionParams,
) => {
  return [`/api/v2/shop/total-product-variant-sales`, ...(params ? [params] : [])] as const;
};

export const getGetTotalProductVariantSaleDTOCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>,
  TError = unknown,
>(
  params?: GetTotalProductVariantSaleDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTotalProductVariantSaleDTOCollectionQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>
  > = ({ signal }) => getTotalProductVariantSaleDTOCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTotalProductVariantSaleDTOCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>
>;
export type GetTotalProductVariantSaleDTOCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of TotalProductVariantSaleDTO resources.
 */
export const useGetTotalProductVariantSaleDTOCollection = <
  TData = Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>,
  TError = unknown,
>(
  params?: GetTotalProductVariantSaleDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTotalProductVariantSaleDTOCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetTotalProductVariantSaleDTOCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a TotalProductVariantSaleDTO resource.
 */
export const getTotalProductVariantSaleDTOItem = (
  id: string,
  params?: GetTotalProductVariantSaleDTOItemParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TotalProductVariantSaleDTOJsonld>(
    { url: `/api/v2/shop/total-product-variant-sales/${id}`, method: "get", params, signal },
    options,
  );
};

export const getGetTotalProductVariantSaleDTOItemQueryKey = (
  id: string,
  params?: GetTotalProductVariantSaleDTOItemParams,
) => {
  return [`/api/v2/shop/total-product-variant-sales/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetTotalProductVariantSaleDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>,
  TError = void,
>(
  id: string,
  params?: GetTotalProductVariantSaleDTOItemParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTotalProductVariantSaleDTOItemQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>> = ({
    signal,
  }) => getTotalProductVariantSaleDTOItem(id, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTotalProductVariantSaleDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>
>;
export type GetTotalProductVariantSaleDTOItemQueryError = void;

/**
 * @summary Retrieves a TotalProductVariantSaleDTO resource.
 */
export const useGetTotalProductVariantSaleDTOItem = <
  TData = Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>,
  TError = void,
>(
  id: string,
  params?: GetTotalProductVariantSaleDTOItemParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTotalProductVariantSaleDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetTotalProductVariantSaleDTOItemQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
