/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Creates a ProductVariantAvailabilityAlert resource.
 */
export const postProductVariantAvailabilityAlertCollection = (
  productVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld: NonReadonly<ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/api/v2/shop/product-variant-availability-alerts`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: productVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld,
    },
    options,
  );
};

export const getPostProductVariantAvailabilityAlertCollectionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProductVariantAvailabilityAlertCollection>>,
    TError,
    { data: NonReadonly<ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProductVariantAvailabilityAlertCollection>>,
  TError,
  { data: NonReadonly<ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProductVariantAvailabilityAlertCollection>>,
    { data: NonReadonly<ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld> }
  > = props => {
    const { data } = props ?? {};

    return postProductVariantAvailabilityAlertCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostProductVariantAvailabilityAlertCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProductVariantAvailabilityAlertCollection>>
>;
export type PostProductVariantAvailabilityAlertCollectionMutationBody =
  NonReadonly<ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld>;
export type PostProductVariantAvailabilityAlertCollectionMutationError = unknown;

/**
 * @summary Creates a ProductVariantAvailabilityAlert resource.
 */
export const usePostProductVariantAvailabilityAlertCollection = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProductVariantAvailabilityAlertCollection>>,
    TError,
    { data: NonReadonly<ProductVariantAvailabilityAlertCreateVariantAvailabilityAlertDTOJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getPostProductVariantAvailabilityAlertCollectionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Retrieves a ProductVariantAvailabilityAlert resource.
 */
export const getProductVariantAvailabilityAlertItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/product-variant-availability-alerts/${id}`, method: "get", signal },
    options,
  );
};

export const getGetProductVariantAvailabilityAlertItemQueryKey = (id: string) => {
  return [`/api/v2/shop/product-variant-availability-alerts/${id}`] as const;
};

export const getGetProductVariantAvailabilityAlertItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductVariantAvailabilityAlertItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>
  > = ({ signal }) => getProductVariantAvailabilityAlertItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProductVariantAvailabilityAlertItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>
>;
export type GetProductVariantAvailabilityAlertItemQueryError = unknown;

/**
 * @summary Retrieves a ProductVariantAvailabilityAlert resource.
 */
export const useGetProductVariantAvailabilityAlertItem = <
  TData = Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProductVariantAvailabilityAlertItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProductVariantAvailabilityAlertItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Removes the ProductVariantAvailabilityAlert resource.
 */
export const deleteProductVariantAvailabilityAlertItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/product-variant-availability-alerts/${id}`, method: "delete" },
    options,
  );
};

export const getDeleteProductVariantAvailabilityAlertItemMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProductVariantAvailabilityAlertItem>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProductVariantAvailabilityAlertItem>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProductVariantAvailabilityAlertItem>>,
    { id: string }
  > = props => {
    const { id } = props ?? {};

    return deleteProductVariantAvailabilityAlertItem(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProductVariantAvailabilityAlertItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProductVariantAvailabilityAlertItem>>
>;

export type DeleteProductVariantAvailabilityAlertItemMutationError = unknown;

/**
 * @summary Removes the ProductVariantAvailabilityAlert resource.
 */
export const useDeleteProductVariantAvailabilityAlertItem = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProductVariantAvailabilityAlertItem>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getDeleteProductVariantAvailabilityAlertItemMutationOptions(options);

  return useMutation(mutationOptions);
};
