/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductAssociationJsonldShopProductAssociationRead } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductAssociation resource.
 */
export const shopGetProductAssociationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductAssociationJsonldShopProductAssociationRead>(
    { url: `/api/v2/shop/product-associations/${id}`, method: "get", signal },
    options,
  );
};

export const getShopGetProductAssociationItemQueryKey = (id: string) => {
  return [`/api/v2/shop/product-associations/${id}`] as const;
};

export const getShopGetProductAssociationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetProductAssociationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductAssociationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetProductAssociationItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetProductAssociationItem>>> = ({
    signal,
  }) => shopGetProductAssociationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetProductAssociationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetProductAssociationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetProductAssociationItem>>
>;
export type ShopGetProductAssociationItemQueryError = void;

/**
 * @summary Retrieves a ProductAssociation resource.
 */
export const useShopGetProductAssociationItem = <
  TData = Awaited<ReturnType<typeof shopGetProductAssociationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductAssociationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetProductAssociationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
