/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ShippingMethodTranslationJsonld } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ShippingMethodTranslation resource.
 */
export const adminGetShippingMethodTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ShippingMethodTranslationJsonld>(
    { url: `/api/v2/admin/shipping-method-translations/${id}`, method: "get", signal },
    options,
  );
};

export const getAdminGetShippingMethodTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/admin/shipping-method-translations/${id}`] as const;
};

export const getAdminGetShippingMethodTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetShippingMethodTranslationItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>
  > = ({ signal }) => adminGetShippingMethodTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetShippingMethodTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>
>;
export type AdminGetShippingMethodTranslationItemQueryError = void;

/**
 * @summary Retrieves a ShippingMethodTranslation resource.
 */
export const useAdminGetShippingMethodTranslationItem = <
  TData = Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetShippingMethodTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetShippingMethodTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a ShippingMethodTranslation resource.
 */
export const shopGetShippingMethodTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ShippingMethodTranslationJsonld>(
    { url: `/api/v2/shop/shipping-method-translations/${id}`, method: "get", signal },
    options,
  );
};

export const getShopGetShippingMethodTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/shop/shipping-method-translations/${id}`] as const;
};

export const getShopGetShippingMethodTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetShippingMethodTranslationItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>
  > = ({ signal }) => shopGetShippingMethodTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetShippingMethodTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>
>;
export type ShopGetShippingMethodTranslationItemQueryError = void;

/**
 * @summary Retrieves a ShippingMethodTranslation resource.
 */
export const useShopGetShippingMethodTranslationItem = <
  TData = Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetShippingMethodTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetShippingMethodTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
