/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductAttributeJsonldShopProductAttributeRead } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductAttribute resource.
 */
export const shopGetProductAttributeItem = (
  code: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductAttributeJsonldShopProductAttributeRead>(
    { url: `/api/v2/shop/product-attributes/${code}`, method: "get", signal },
    options,
  );
};

export const getShopGetProductAttributeItemQueryKey = (code: string) => {
  return [`/api/v2/shop/product-attributes/${code}`] as const;
};

export const getShopGetProductAttributeItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetProductAttributeItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetProductAttributeItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetProductAttributeItemQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetProductAttributeItem>>> = ({
    signal,
  }) => shopGetProductAttributeItem(code, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetProductAttributeItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetProductAttributeItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetProductAttributeItem>>
>;
export type ShopGetProductAttributeItemQueryError = void;

/**
 * @summary Retrieves a ProductAttribute resource.
 */
export const useShopGetProductAttributeItem = <
  TData = Awaited<ReturnType<typeof shopGetProductAttributeItem>>,
  TError = void,
>(
  code: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetProductAttributeItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetProductAttributeItemQueryOptions(code, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
