/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAuctionCatalogCollection200,
  GetAuctionCatalogCollectionParams,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a AuctionCatalog resource.
 */
export const getAuctionCatalogItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/auction-catalogs/${id}`, method: "get", signal },
    options,
  );
};

export const getGetAuctionCatalogItemQueryKey = (id: string) => {
  return [`/api/v2/auction-catalogs/${id}`] as const;
};

export const getGetAuctionCatalogItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuctionCatalogItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionCatalogItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuctionCatalogItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuctionCatalogItem>>> = ({ signal }) =>
    getAuctionCatalogItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuctionCatalogItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuctionCatalogItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuctionCatalogItem>>
>;
export type GetAuctionCatalogItemQueryError = unknown;

/**
 * @summary Retrieves a AuctionCatalog resource.
 */
export const useGetAuctionCatalogItem = <
  TData = Awaited<ReturnType<typeof getAuctionCatalogItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionCatalogItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuctionCatalogItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves the collection of AuctionCatalog resources.
 */
export const getAuctionCatalogCollection = (
  params?: GetAuctionCatalogCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetAuctionCatalogCollection200>(
    { url: `/api/v2/shop/auction-catalogs`, method: "get", params, signal },
    options,
  );
};

export const getGetAuctionCatalogCollectionQueryKey = (
  params?: GetAuctionCatalogCollectionParams,
) => {
  return [`/api/v2/shop/auction-catalogs`, ...(params ? [params] : [])] as const;
};

export const getGetAuctionCatalogCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuctionCatalogCollection>>,
  TError = unknown,
>(
  params?: GetAuctionCatalogCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionCatalogCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuctionCatalogCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuctionCatalogCollection>>> = ({
    signal,
  }) => getAuctionCatalogCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuctionCatalogCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuctionCatalogCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuctionCatalogCollection>>
>;
export type GetAuctionCatalogCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of AuctionCatalog resources.
 */
export const useGetAuctionCatalogCollection = <
  TData = Awaited<ReturnType<typeof getAuctionCatalogCollection>>,
  TError = unknown,
>(
  params?: GetAuctionCatalogCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionCatalogCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuctionCatalogCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
