/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetRelayPointDTOCollectionParams,
  RelayPointDTOJsonld,
  RelayPointDTORelayPointInputDataDTOJsonld,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of RelayPointDTO resources.
 */
export const getRelayPointDTOCollection = (
  params?: GetRelayPointDTOCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/relay-point-d-t-os`, method: "get", params, signal },
    options,
  );
};

export const getGetRelayPointDTOCollectionQueryKey = (
  params?: GetRelayPointDTOCollectionParams,
) => {
  return [`/api/v2/shop/relay-point-d-t-os`, ...(params ? [params] : [])] as const;
};

export const getGetRelayPointDTOCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getRelayPointDTOCollection>>,
  TError = unknown,
>(
  params?: GetRelayPointDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRelayPointDTOCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRelayPointDTOCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRelayPointDTOCollection>>> = ({
    signal,
  }) => getRelayPointDTOCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRelayPointDTOCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRelayPointDTOCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRelayPointDTOCollection>>
>;
export type GetRelayPointDTOCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of RelayPointDTO resources.
 */
export const useGetRelayPointDTOCollection = <
  TData = Awaited<ReturnType<typeof getRelayPointDTOCollection>>,
  TError = unknown,
>(
  params?: GetRelayPointDTOCollectionParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRelayPointDTOCollection>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRelayPointDTOCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a RelayPointDTO resource.
 */
export const getRelayPointDTOItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/relay-point-d-t-os/${id}`, method: "get", signal },
    options,
  );
};

export const getGetRelayPointDTOItemQueryKey = (id: string) => {
  return [`/api/v2/shop/relay-point-d-t-os/${id}`] as const;
};

export const getGetRelayPointDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getRelayPointDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRelayPointDTOItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRelayPointDTOItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRelayPointDTOItem>>> = ({ signal }) =>
    getRelayPointDTOItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRelayPointDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRelayPointDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRelayPointDTOItem>>
>;
export type GetRelayPointDTOItemQueryError = unknown;

/**
 * @summary Retrieves a RelayPointDTO resource.
 */
export const useGetRelayPointDTOItem = <
  TData = Awaited<ReturnType<typeof getRelayPointDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRelayPointDTOItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRelayPointDTOItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Creates a RelayPointDTO resource.
 */
export const postRelayPointDTOCollection = (
  relayPointDTORelayPointInputDataDTOJsonld: NonReadonly<RelayPointDTORelayPointInputDataDTOJsonld>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<RelayPointDTOJsonld>(
    {
      url: `/api/v2/shop/send-relay-points`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: relayPointDTORelayPointInputDataDTOJsonld,
    },
    options,
  );
};

export const getPostRelayPointDTOCollectionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRelayPointDTOCollection>>,
    TError,
    { data: NonReadonly<RelayPointDTORelayPointInputDataDTOJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRelayPointDTOCollection>>,
  TError,
  { data: NonReadonly<RelayPointDTORelayPointInputDataDTOJsonld> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRelayPointDTOCollection>>,
    { data: NonReadonly<RelayPointDTORelayPointInputDataDTOJsonld> }
  > = props => {
    const { data } = props ?? {};

    return postRelayPointDTOCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRelayPointDTOCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRelayPointDTOCollection>>
>;
export type PostRelayPointDTOCollectionMutationBody =
  NonReadonly<RelayPointDTORelayPointInputDataDTOJsonld>;
export type PostRelayPointDTOCollectionMutationError = void;

/**
 * @summary Creates a RelayPointDTO resource.
 */
export const usePostRelayPointDTOCollection = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRelayPointDTOCollection>>,
    TError,
    { data: NonReadonly<RelayPointDTORelayPointInputDataDTOJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getPostRelayPointDTOCollectionMutationOptions(options);

  return useMutation(mutationOptions);
};
