/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductTranslationJsonld } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductTranslation resource.
 */
export const adminGetProductTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductTranslationJsonld>(
    { url: `/api/v2/admin/product-translations/${id}`, method: "get", signal },
    options,
  );
};

export const getAdminGetProductTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/admin/product-translations/${id}`] as const;
};

export const getAdminGetProductTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetProductTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetProductTranslationItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetProductTranslationItem>>> = ({
    signal,
  }) => adminGetProductTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetProductTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetProductTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetProductTranslationItem>>
>;
export type AdminGetProductTranslationItemQueryError = void;

/**
 * @summary Retrieves a ProductTranslation resource.
 */
export const useAdminGetProductTranslationItem = <
  TData = Awaited<ReturnType<typeof adminGetProductTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetProductTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a ProductTranslation resource.
 */
export const shopGetProductTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductTranslationJsonld>(
    { url: `/api/v2/shop/product-translations/${id}`, method: "get", signal },
    options,
  );
};

export const getShopGetProductTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/shop/product-translations/${id}`] as const;
};

export const getShopGetProductTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetProductTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetProductTranslationItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetProductTranslationItem>>> = ({
    signal,
  }) => shopGetProductTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetProductTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetProductTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetProductTranslationItem>>
>;
export type ShopGetProductTranslationItemQueryError = void;

/**
 * @summary Retrieves a ProductTranslation resource.
 */
export const useShopGetProductTranslationItem = <
  TData = Awaited<ReturnType<typeof shopGetProductTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetProductTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
