/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a OrderAmountValidationOutputDTO resource.
 */
export const getOrderAmountValidationOutputDTOItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/order-amount-validation-output-d-t-os/${id}`, method: "get", signal },
    options,
  );
};

export const getGetOrderAmountValidationOutputDTOItemQueryKey = (id: string) => {
  return [`/api/v2/order-amount-validation-output-d-t-os/${id}`] as const;
};

export const getGetOrderAmountValidationOutputDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOrderAmountValidationOutputDTOItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>
  > = ({ signal }) => getOrderAmountValidationOutputDTOItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOrderAmountValidationOutputDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>
>;
export type GetOrderAmountValidationOutputDTOItemQueryError = unknown;

/**
 * @summary Retrieves a OrderAmountValidationOutputDTO resource.
 */
export const useGetOrderAmountValidationOutputDTOItem = <
  TData = Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOrderAmountValidationOutputDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetOrderAmountValidationOutputDTOItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
