/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a PaymentProcessingOutputDTO resource.
 */
export const getPaymentProcessingOutputDTOItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/payment-processing-output-d-t-os/${id}`, method: "get", signal },
    options,
  );
};

export const getGetPaymentProcessingOutputDTOItemQueryKey = (id: string) => {
  return [`/api/v2/payment-processing-output-d-t-os/${id}`] as const;
};

export const getGetPaymentProcessingOutputDTOItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPaymentProcessingOutputDTOItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>> = ({
    signal,
  }) => getPaymentProcessingOutputDTOItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPaymentProcessingOutputDTOItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>
>;
export type GetPaymentProcessingOutputDTOItemQueryError = unknown;

/**
 * @summary Retrieves a PaymentProcessingOutputDTO resource.
 */
export const useGetPaymentProcessingOutputDTOItem = <
  TData = Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPaymentProcessingOutputDTOItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetPaymentProcessingOutputDTOItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
