import { PLPIndexName, RefinementList } from "@/hooks/useAlgoliaRefinements";
import { Locale } from "@/urls/linksTranslation";

export type RefinementType = keyof RefinementList | "query" | "page" | "sortBy";
export type RefinementTranslationType = "enum" | "identical" | "transform" | "boolean" | "query";

export interface CodeToTranslatedEnum {
  translatedKey: Record<Locale, string>;
  translatedValues: Record<string, Record<Locale, string>>;
  type: "enum";
  priority: number;
}

interface CodeToTranslatedOther {
  translatedKey: Record<Locale, string>;
  type: Exclude<RefinementTranslationType, "enum">;
  priority: number;
}

export type ValueTranslatedToCode = Record<string, Record<string, string>>;
export type KeyTranslatedToCode = Record<
  string,
  { name: RefinementType; type: RefinementTranslationType }
>;

export type CodeToTranslated = Record<
  RefinementType,
  CodeToTranslatedEnum | CodeToTranslatedOther
> & { grapeVariety: CodeToTranslatedEnum };
export type KeyList = {
  name: RefinementType;
  type: RefinementTranslationType;
}[];
type TempKeyList = {
  name: RefinementType;
  type: RefinementTranslationType;
  priority: number;
}[];
export type ValueSeparator = Record<Locale, string>;
export type CustomSorts = Record<"color" | "bottleSize" | "region", Record<string, number>>;

export const paramsList: RefinementType[] = ["sortBy"];

export const valueSeparator: ValueSeparator = {
  en: "or",
  fr: "ou",
  it: "o",
  de: "oder",
};

export const customSorts: CustomSorts = {
  region: {
    Bordeaux: 0,
    Bourgogne: 1,
    "Vallée du Rhone": 2,
  },
  bottleSize: {
    Bouteille: 0,
    Magnum: 1,
    "Demi-bouteille": 2,
  },
  color: {
    Rouge: 0,
    Blanc: 1,
    Rosé: 2,
    "Blanc Effervescent": 3,
  },
};

export const codeToTranslated: CodeToTranslated = {
  isDirectPurchase: {
    translatedKey: {
      en: "sale",
      fr: "vente",
      it: "vendita",
      de: "verkauf",
    },
    translatedValues: {
      true: { en: "vente-flash", fr: "vente-flash", it: "vente-flash", de: "vente-flash" },
      false: { en: "vente-on-line", fr: "vente-on-line", it: "vente-on-line", de: "vente-on-line" },
    },
    type: "enum",
    priority: 0,
  },
  country: {
    translatedKey: {
      en: "country",
      fr: "pays",
      it: "paese",
      de: "land",
    },
    translatedValues: {
      AFRIQUE_DU_SUD: {
        en: "south-africa",
        fr: "afrique-du-sud",
        it: "sudafrica",
        de: "sudafrika",
      },
      ALLEMAGNE: { en: "germany", fr: "allemagne", it: "germania", de: "deutschland" },
      ARMENIE: { en: "armenie", fr: "armenia", it: "armenia", de: "armenien" },
      ANTIGUA_ET_BARBUDA: {
        en: "antigua-and-barbuda",
        fr: "antigua-et-barbuda",
        it: "antigua-e-barbuda",
        de: "antigua-und-barbuda",
      },
      ANTILLES: { en: "antilles", fr: "antilles", it: "antille", de: "antillen" },
      ARGENTINE: { en: "argentina", fr: "argentine", it: "argentina", de: "argentinien" },
      AUSTRALIE: { en: "australia", fr: "australie", it: "australia", de: "australien" },
      AUTRES_PAYS: {
        en: "other",
        fr: "autres",
        it: "altri",
        de: "andere",
      },
      AUTRICHE: { en: "austria", fr: "autriche", it: "austria", de: "osterreich" },
      BAHAMAS: { en: "bahamas", fr: "bahamas", it: "bahamas", de: "bahamas" },
      BARBADE: { en: "barbados", fr: "barbade", it: "barbados", de: "barbados" },
      BELGIQUE: { en: "belgium", fr: "belgique", it: "belgio", de: "belgien" },
      BELIZE: { en: "belize", fr: "belize", it: "belize", de: "belize" },
      BERMUDES: { en: "bermuda", fr: "bermudes", it: "bermuda", de: "bermuda" },
      BOSNIE_HERZEGOVINE: {
        en: "bosnia-and-herzegovina",
        fr: "bosnie-herzegovine",
        it: "bosnia-erzegovina",
        de: "bosnien-und-herzegowina",
      },
      BRESIL: { en: "brazil", fr: "bresil", it: "brasile", de: "brasilien" },
      CANADA: { en: "canada", fr: "canada", it: "canada", de: "kanada" },
      CAP_VERT: { en: "cape-verde", fr: "cap-vert", it: "capo-verde", de: "kap-verde" },
      CARAIBES: { en: "caribbean", fr: "caraibes", it: "caraibi", de: "karibik" },
      CHILI: { en: "chile", fr: "chili", it: "cile", de: "chile" },
      CHINE: { en: "china", fr: "chine", it: "cina", de: "china" },
      COLOMBIE: { en: "colombia", fr: "colombie", it: "colombia", de: "kolumbien" },
      CROATIE: { en: "croatia", fr: "croatie", it: "croazia", de: "kroatien" },
      CUBA: { en: "cuba", fr: "cuba", it: "cuba", de: "kuba" },
      DANEMARK: { en: "denmark", fr: "danemark", it: "danimarca", de: "danemark" },
      ECOSSE: { en: "scotland", fr: "ecosse", it: "scozia", de: "schottland" },
      ESPAGNE: { en: "spain", fr: "espagne", it: "spagna", de: "spanien" },
      ETATS_UNIS: {
        en: "united-states",
        fr: "etats-unis",
        it: "stati-uniti",
        de: "vereinigte-staaten",
      },
      FIDJI: { en: "fiji", fr: "fidji", it: "figi", de: "fidschi" },
      FRANCE: { en: "france", fr: "france", it: "francia", de: "frankreich" },
      GRECE: { en: "greece", fr: "grece", it: "grecia", de: "griechenland" },
      GRENADE: { en: "grenada", fr: "grenade", it: "grenada", de: "grenada" },
      GUADELOUPE: { en: "guadeloupe", fr: "guadeloupe", it: "guadalupa", de: "guadeloupe" },
      GUATEMALA: { en: "guatemala", fr: "guatemala", it: "guatemala", de: "guatemala" },
      GUYANA: { en: "guyana", fr: "guyana", it: "guyana", de: "guyana" },
      GUYANE: {
        en: "french-guiana",
        fr: "guyane",
        it: "guyana-francese",
        de: "franzosisch-guayana",
      },
      HAITI: { en: "haiti", fr: "haiti", it: "haiti", de: "haiti" },
      HONGRIE: { en: "hungary", fr: "hongrie", it: "ungheria", de: "ungarn" },
      ILE_MAURICE: { en: "mauritius", fr: "ile-maurice", it: "mauritius", de: "mauritius" },
      INDE: { en: "india", fr: "inde", it: "india", de: "indien" },
      IRLANDE: { en: "ireland", fr: "irelande", it: "irlanda", de: "irland" },
      ISRAEL: { en: "israel", fr: "israel", it: "israele", de: "israel" },
      ITALIE: { en: "italy", fr: "italie", it: "italia", de: "italien" },
      JAMAIQUE: { en: "jamaica", fr: "jamaique", it: "giamaica", de: "jamaika" },
      JAPON: { en: "japan", fr: "japon", it: "giappone", de: "japan" },
      KENYA: { en: "kenya", fr: "kenya", it: "kenya", de: "kenia" },
      LA_REUNION: { en: "reunion", fr: "la-reunion", it: "riunione", de: "reunion" },
      LIBAN: { en: "lebanon", fr: "liban", it: "libano", de: "libanon" },
      MACEDOINE: { en: "macedonia", fr: "macedoine", it: "macedonia", de: "mazedonien" },
      MADAGASCAR: { en: "madagascar", fr: "madagascar", it: "madagascar", de: "madagaskar" },
      MAROC: { en: "morocco", fr: "maroc", it: "marocco", de: "marokko" },
      MARTINIQUE: { en: "martinique", fr: "martinique", it: "martinica", de: "martinique" },
      MEXIQUE: { en: "mexico", fr: "mexique", it: "messico", de: "mexiko" },
      NEPAL: { en: "nepal", fr: "nepal", it: "nepal", de: "nepal" },
      NICARAGUA: { en: "nicaragua", fr: "nicaragua", it: "nicaragua", de: "nicaragua" },
      NOUVELLE_ZELANDE: {
        en: "new-zealand",
        fr: "nouvelle-zelande",
        it: "nuova-zelanda",
        de: "neuseeland",
      },
      PANAMA: { en: "panama", fr: "panama", it: "panama", de: "panama" },
      PEROU: { en: "peru", fr: "perou", it: "perù", de: "peru" },
      PHILIPPINES: { en: "philippines", fr: "philippines", it: "filippine", de: "philippinen" },
      POLOGNE: { en: "poland", fr: "pologne", it: "polonia", de: "polen" },
      POLYNESIE_FRANCAISE: {
        en: "french-polynesia",
        fr: "polynesie-française",
        it: "polinesia-francese",
        de: "franzosisch-polynesien",
      },
      PORTO_RICO: { en: "puerto-rico", fr: "porto-rico", it: "porto-rico", de: "puerto-rico" },
      PORTUGAL: { en: "portugal", fr: "portugal", it: "portogallo", de: "portugal" },
      REPUBLIQUE_DOMINICAINE: {
        en: "dominican-republic",
        fr: "republique-dominicaine",
        it: "repubblica-dominicana",
        de: "dominikanische-republik",
      },
      REPUBLIQUE_TCHEQUE: {
        en: "czech-republic",
        fr: "republique-tcheque",
        it: "repubblica-ceca",
        de: "tschechische-republik",
      },
      ROYAUME_UNI: {
        en: "united-kingdom",
        fr: "royaume-uni",
        it: "regno-unito",
        de: "vereinigtes-konigreich",
      },
      RUSSIE: { en: "russia", fr: "russie", it: "russia", de: "russland" },
      SAINT_MARTIN: {
        en: "saint-martin",
        fr: "saint-martin",
        it: "saint-martin",
        de: "saint-martin",
      },
      SAINTE_LUCIE: {
        en: "saint-lucia",
        fr: "sainte-lucie",
        it: "santa-lucia",
        de: "saint-lucia",
      },
      SEYCHELLES: { en: "seychelles", fr: "seychelles", it: "seychelles", de: "seychellen" },
      SLOVAQUIE: { en: "slovakia", fr: "slovaquie", it: "slovacchia", de: "slowakei" },
      SLOVENIE: { en: "slovenia", fr: "slovenie", it: "slovenia", de: "slowenien" },
      SRI_LANKA: { en: "sri-lanka", fr: "sri-lanka", it: "sri-lanka", de: "sri-lanka" },
      SUEDE: { en: "sweden", fr: "suede", it: "svezia", de: "schweden" },
      SUISSE: { en: "switzerland", fr: "suisse", it: "svizzera", de: "schweiz" },
      TAIWAN: { en: "taiwan", fr: "taiwan", it: "taiwan", de: "taiwan" },
      TCHECOSLOVAQUIE: {
        en: "czechoslovakia",
        fr: "tchecoslovaquie",
        it: "cecoslovacchia",
        de: "tschechoslowakei",
      },
      TRINITE_ET_TOBAGO: {
        en: "trinidad-and-tobago",
        fr: "trinite-et-tobago",
        it: "trinidad-e-tobago",
        de: "trinidad-und-tobago",
      },
      URUGUAY: { en: "uruguay", fr: "uruguay", it: "uruguay", de: "uruguay" },
      VENEZUELA: { en: "venezuela", fr: "venezuela", it: "venezuela", de: "venezuela" },
    },
    type: "enum",
    priority: 1,
  },
  region: {
    translatedKey: {
      en: "region",
      fr: "region",
      it: "regione",
      de: "region",
    },
    translatedValues: {
      ABRUZZES: { en: "abruzzo", fr: "abruzzes", it: "abruzzo", de: "abruzzen" },
      ADELAIDE_HILLS: {
        en: "adelaide-hills",
        fr: "adelaide-hills",
        it: "colline-di-adelaide",
        de: "adelaide-hills",
      },
      AFRIQUE_DU_SUD: {
        en: "south-africa",
        fr: "afrique-du-sud",
        it: "sudafrica",
        de: "sudafrika",
      },
      ALLEMAGNE: { en: "germany", fr: "allemagne", it: "germania", de: "deutschland" },
      ALSACE: { en: "alsace", fr: "alsace", it: "alsazia", de: "elsass" },
      ANDALOUSIE: { en: "andalusia", fr: "andalousie", it: "andalusia", de: "andalusien" },
      ANGLETERRE: { en: "england", fr: "angleterre", it: "inghilterra", de: "england" },
      ANTIGUE_ET_BARBUDE: {
        en: "antigua-and-barbuda",
        fr: "antigue-et-barbude",
        it: "antigua-e-barbuda",
        de: "antigua-und-barbuda",
      },
      ANTILLES: { en: "antilles", fr: "antilles", it: "antille", de: "antillen" },
      ANTRIM_COUNTY: {
        en: "antrim-county",
        fr: "antrim-county",
        it: "contea-di-antrim",
        de: "antrim-county",
      },
      ARAGON: { en: "aragon", fr: "aragon", it: "aragona", de: "aragonien" },
      ARGENTINE: { en: "argentina", fr: "argentine", it: "argentina", de: "argentinien" },
      AUCKLAND: { en: "auckland", fr: "auckland", it: "auckland", de: "auckland" },
      AUSTRALIE: { en: "australia", fr: "australie", it: "australia", de: "australien" },
      AUTRES_REGIONS: {
        en: "other",
        fr: "autres",
        it: "altre",
        de: "andere",
      },
      AUTRICHE: { en: "austria", fr: "autriche", it: "austria", de: "osterreich" },
      AUVERGNE: { en: "auvergne", fr: "auvergne", it: "alvernia", de: "auvergne" },
      BAHAMAS: { en: "bahamas", fr: "bahamas", it: "bahamas", de: "bahamas" },
      BALEARES: { en: "balearic-islands", fr: "baleares", it: "baleari", de: "balearen" },
      BANGALORE: { en: "bangalore", fr: "bangalore", it: "bangalore", de: "bangalore" },
      BARBADE: { en: "barbados", fr: "barbade", it: "barbados", de: "barbados" },
      BAROSSA_VALLEY: {
        en: "barossa-valley",
        fr: "barossa-valley",
        it: "valle-di-barossa",
        de: "barossa-tal",
      },
      BASILICATA: { en: "basilicata", fr: "basilicata", it: "basilicata", de: "basilikata" },
      BEAUJOLAIS: { en: "beaujolais", fr: "beaujolais", it: "beaujolais", de: "beaujolais" },
      BEKAA: { en: "bekaa", fr: "bekaa", it: "bekaa", de: "bekaa" },
      BELGIQUE: { en: "belgium", fr: "belgique", it: "belgio", de: "belgien" },
      BELIZE: { en: "belize", fr: "belize", it: "belize", de: "belize" },
      BERMUDES: { en: "bermuda", fr: "bermudes", it: "bermuda", de: "bermuda" },
      BORDEAUX: { en: "bordeaux", fr: "bordeaux", it: "bordeaux", de: "bordeaux" },
      BOSNIE_HERZEGOVINE: {
        en: "bosnia-and-herzegovina",
        fr: "bosnie-herzegovine",
        it: "bosnia-erzegovina",
        de: "bosnien-und-herzegowina",
      },
      BOURGOGNE: { en: "burgundy", fr: "bourgogne", it: "borgogna", de: "burgund" },
      BRESIL: { en: "brazil", fr: "bresil", it: "brasile", de: "brasilien" },
      BRETAGNE: { en: "brittany", fr: "bretagne", it: "bretagna", de: "bretagne" },
      BURGENLAND: { en: "burgenland", fr: "burgenland", it: "burgenland", de: "burgenland" },
      CALIFORNIE: { en: "california", fr: "californie", it: "california", de: "kalifornien" },
      CAMPANIE: { en: "campania", fr: "campanie", it: "campania", de: "kampanien" },
      CAMPBELTOWN: { en: "campbeltown", fr: "campbeltown", it: "campbeltown", de: "campbeltown" },
      CANADA: { en: "canada", fr: "canada", it: "canada", de: "kanada" },
      CANTERBURY: { en: "canterbury", fr: "canterbury", it: "canterbury", de: "canterbury" },
      CAP_VERT: { en: "cape-verde", fr: "cap-vert", it: "capo-verde", de: "kap-verde" },
      CARAIBES: { en: "caribbean", fr: "caraibes", it: "caraibi", de: "karibik" },
      CASTILLE_ET_LEON: {
        en: "castile-and-león",
        fr: "castille-et-leon",
        it: "castiglia-e-león",
        de: "kastilien-und-león",
      },
      CASTILLE_LA_MANCHE: {
        en: "castile-la-mancha",
        fr: "castille-la-manche",
        it: "castiglia-la-mancia",
        de: "kastilien-la-mancha",
      },
      CATALOGNE: { en: "catalonia", fr: "catalogne", it: "catalogna", de: "katalonien" },
      CENTRAL_OTAGO: {
        en: "central-otago",
        fr: "central-otago",
        it: "otago-centrale",
        de: "zentral-otago",
      },
      CHAMPAGNE: { en: "champagne", fr: "champagne", it: "champagne", de: "champagne" },
      CHARENTE: { en: "charente", fr: "charente", it: "charente", de: "charente" },
      CHILI: { en: "chile", fr: "chili", it: "cile", de: "chile" },
      CHINE: { en: "china", fr: "chine", it: "cina", de: "china" },
      CLARE_VALLEY: {
        en: "clare-valley",
        fr: "clare-valley",
        it: "valle-di-clare",
        de: "clare-valley",
      },
      COLCHAGUA: { en: "colchagua", fr: "colchagua", it: "colchagua", de: "colchagua" },
      COLOMBIE: { en: "colombia", fr: "colombie", it: "colombia", de: "kolumbien" },
      CORK_COUNTY: {
        en: "cork-county",
        fr: "cork-county",
        it: "contea-di-cork",
        de: "cork-county",
      },
      CORSE: { en: "corsica", fr: "corse", it: "corsica", de: "korsika" },
      COTE_CENTRALE: {
        en: "central-coast-australia",
        fr: "cote-centrale-australie",
        it: "costa-centrale-australia",
        de: "central-coast-australien",
      },
      COTE_CENTRALE_USA: {
        en: "central-coast-united-states",
        fr: "cote-centrale-etats-unis",
        it: "costa-centrale-stati-uniti",
        de: "central-coast-vereinigte-staaten",
      },
      CROATIE: { en: "croatia", fr: "croatie", it: "croazia", de: "kroatien" },
      CUBA: { en: "cuba", fr: "cuba", it: "cuba", de: "kuba" },
      DANEMARK: { en: "denmark", fr: "danemark", it: "danimarca", de: "danemark" },
      DEMERARA_MAHAICA: {
        en: "demerara-mahaica",
        fr: "demerara-mahaica",
        it: "demerara-mahaica",
        de: "demerara-mahaica",
      },
      DIVERS: { en: "various", fr: "divers", it: "varie", de: "verschiedenes" },
      DUBLIN_COUNTY: {
        en: "dublin-county",
        fr: "dublin-county",
        it: "contea-di-dublino",
        de: "dublin-county",
      },
      ECOSSE: { en: "scotland", fr: "ecosse", it: "scozia", de: "schottland" },
      EDEN_VALLEY: {
        en: "eden-valley",
        fr: "eden-valley",
        it: "valle-dell'eden",
        de: "eden-valley",
      },
      EMILIE_ROMAGNE: {
        en: "emilia-romagna",
        fr: "emilie-romagne",
        it: "emilia-romagna",
        de: "emilia-romagna",
      },
      ESPAGNE: { en: "spain", fr: "espagne", it: "spagna", de: "spanien" },
      ETATS_UNIS: {
        en: "united-states",
        fr: "etats-unis",
        it: "stati-uniti",
        de: "vereinigte-staaten",
      },
      FIDJI: { en: "fiji", fr: "fidji", it: "figi", de: "fidschi" },
      FINGER_LAKES: {
        en: "finger-lakes",
        fr: "finger-lakes",
        it: "finger-lakes",
        de: "finger-lakes",
      },
      FRANCE: { en: "france", fr: "france", it: "francia", de: "frankreich" },
      FRANSCHHOEK: { en: "franschhoek", fr: "franschhoek", it: "franschhoek", de: "franschhoek" },
      FRIBOURG: { en: "fribourg", fr: "fribourg", it: "friburgo", de: "freiburg" },
      FRIOUL: { en: "friuli", fr: "frioul", it: "friuli", de: "friaul" },
      FRIOUL_VENETIE_JULIENNE: {
        en: "friuli-venezia-giulia",
        fr: "frioul-venetie-julienne",
        it: "friuli-venezia-giulia",
        de: "friaul-julisch-venetien",
      },
      GALICE: { en: "galicia", fr: "galice", it: "galizia", de: "galicien" },
      GALLES_DU_SUD: {
        en: "south-wales",
        fr: "galles-du-sud",
        it: "galles-del-sud",
        de: "sudwales",
      },
      GAVLEBORG_COUNTY: {
        en: "gavleborg-county",
        fr: "gavleborg-county",
        it: "contea-di-gavleborg",
        de: "gavleborg-county",
      },
      GRANDE_BRETAGNE: {
        en: "great-britain",
        fr: "grande-bretagne",
        it: "gran-bretagna",
        de: "großbritannien",
      },
      GRECE: { en: "greece", fr: "grece", it: "grecia", de: "griechenland" },
      GRENADE: { en: "grenada", fr: "grenade", it: "grenada", de: "grenada" },
      GRISONS: { en: "grisons", fr: "grisons", it: "grisons", de: "graubunden" },
      GUADELOUPE: { en: "guadeloupe", fr: "guadeloupe", it: "guadalupa", de: "guadeloupe" },
      GUATEMALA: { en: "guatemala", fr: "guatemala", it: "guatemala", de: "guatemala" },
      GUYANE: { en: "guyana", fr: "guyane", it: "guyana", de: "guyana" },
      GUYANE_BRITANNIQUE: {
        en: "british-guiana",
        fr: "guyane-britannique",
        it: "guyana-britannica",
        de: "britisch-guayana",
      },
      HAITI: { en: "haiti", fr: "haiti", it: "haiti", de: "haiti" },
      HAWAI: { en: "hawaii", fr: "hawai", it: "hawaii", de: "hawaii" },
      HAWKE_S_BAY: { en: "hawke's-bay", fr: "hawke-s-bay", it: "baia-di-hawke", de: "hawke's-bay" },
      HIGHLANDS: { en: "highlands", fr: "highlands", it: "altipiani", de: "highlands" },
      HIGLANDS_ARRAN: {
        en: "highlands-arran",
        fr: "higlands-arran",
        it: "highlands-arran",
        de: "highlands-arran",
      },
      HIGLANDS_JURA: {
        en: "highlands-jura",
        fr: "higlands-jura",
        it: "highlands-jura",
        de: "highlands-jura",
      },
      HIGLANDS_MULL: {
        en: "highlands-mull",
        fr: "higlands-mull",
        it: "highlands-mull",
        de: "highlands-mull",
      },
      HIGLANDS_ORKNEY: {
        en: "highlands-orkney",
        fr: "higlands-orkney",
        it: "highlands-orkney",
        de: "highlands-orkney",
      },
      HIGLANDS_SKYE: {
        en: "highlands-skye",
        fr: "higlands-skye",
        it: "highlands-skye",
        de: "highlands-skye",
      },
      HOKKAIDO: { en: "hokkaido", fr: "hokkaido", it: "hokkaido", de: "hokkaido" },
      HONGRIE: { en: "hungary", fr: "hongrie", it: "ungheria", de: "ungarn" },
      HONSHU: { en: "honshu", fr: "honshu", it: "honshu", de: "honshu" },
      HONSHU_AOMORI: {
        en: "honshu-aomori",
        fr: "honshu-aomori",
        it: "honshu-aomori",
        de: "honshu-aomori",
      },
      HONSHU_HYOGO: {
        en: "honshu-hyogo",
        fr: "honshu-hyogo",
        it: "honshu-hyogo",
        de: "honshu-hyogo",
      },
      HONSHU_KANAWAGA: {
        en: "honshu-kanawaga",
        fr: "honshu-kanawaga",
        it: "honshu-kanawaga",
        de: "honshu-kanawaga",
      },
      HONSHU_KYOTO: {
        en: "honshu-kyoto",
        fr: "honshu-kyoto",
        it: "honshu-kyoto",
        de: "honshu-kyoto",
      },
      HONSHU_MIYAGI: {
        en: "honshu-miyagi",
        fr: "honshu-miyagi",
        it: "honshu-miyagi",
        de: "honshu-miyagi",
      },
      HONSHU_NAGANO: {
        en: "honshu-nagano",
        fr: "honshu-nagano",
        it: "honshu-nagano",
        de: "honshu-nagano",
      },
      HONSHU_OSAKA: {
        en: "honshu-osaka",
        fr: "honshu-osaka",
        it: "honshu-osaka",
        de: "honshu-osaka",
      },
      HONSHU_SAITAMA: {
        en: "honshu-saitama",
        fr: "honshu-saitama",
        it: "honshu-saitama",
        de: "honshu-saitama",
      },
      HONSHU_YAMAGATA: {
        en: "honshu-yamagata",
        fr: "honshu-yamagata",
        it: "honshu-yamagata",
        de: "honshu-yamagata",
      },
      HONSHU_YAMANASHI: {
        en: "honshu-yamanashi",
        fr: "honshu-yamanashi",
        it: "honshu-yamanashi",
        de: "honshu-yamanashi",
      },
      INDE: { en: "india", fr: "inde", it: "india", de: "indien" },
      INDIANA: { en: "indiana", fr: "indiana", it: "indiana", de: "indiana" },
      IRLANDE: { en: "ireland", fr: "irlande", it: "irlanda", de: "irland" },
      ISLAND_OF_NEGROS: {
        en: "island-of-negros",
        fr: "island-of-negros",
        it: "isola-di-negros",
        de: "insel-negros",
      },
      ISLAY: { en: "islay", fr: "islay", it: "islay", de: "islay" },
      ISRAEL: { en: "israel", fr: "israel", it: "israele", de: "israel" },
      ITALIE: { en: "italy", fr: "italie", it: "italia", de: "italien" },
      JALISCO: { en: "jalisco", fr: "jalisco", it: "jalisco", de: "jalisco" },
      JAMAIQUE: { en: "jamaica", fr: "jamaique", it: "giamaica", de: "jamaika" },
      JAPON: { en: "japan", fr: "japon", it: "giappone", de: "japan" },
      JURA: { en: "jura", fr: "jura", it: "jura", de: "jura" },
      JUZNOSLOVENSKA: {
        en: "south-slovenia",
        fr: "juznoslovenska",
        it: "juznoslovenska",
        de: "juznoslovenska",
      },
      KAMPTAL: { en: "kamptal", fr: "kamptal", it: "kamptal", de: "kamptal" },
      KENTUCKY: { en: "kentucky", fr: "kentucky", it: "kentucky", de: "kentucky" },
      KENYA: { en: "kenya", fr: "kenya", it: "kenya", de: "kenia" },
      LA_REUNION: { en: "reunion", fr: "la-reunion", it: "la-riunione", de: "reunion" },
      LANGHORNE_CREEK: {
        en: "langhorne-creek",
        fr: "langhorne-creek",
        it: "langhorne-creek",
        de: "langhorne-creek",
      },
      LANGUEDOC: { en: "languedoc", fr: "languedoc", it: "languedoc", de: "languedoc" },
      LANZAROTE: { en: "lanzarote", fr: "lanzarote", it: "lanzarote", de: "lanzarote" },
      LIBAN: { en: "lebanon", fr: "liban", it: "libano", de: "libanon" },
      LIGURIE: { en: "liguria", fr: "ligurie", it: "liguria", de: "ligurien" },
      LOMBARDIE: { en: "lombardy", fr: "lombardie", it: "lombardia", de: "lombardei" },
      LOWLANDS: { en: "lowlands", fr: "lowlands", it: "lowlands", de: "lowlands" },
      MACEDOINE: { en: "macedonia", fr: "macedoine", it: "macedonia", de: "mazedonien" },
      MADAGASCAR: { en: "madagascar", fr: "madagascar", it: "madagascar", de: "madagaskar" },
      MADERE: { en: "madeira", fr: "madere", it: "madeira", de: "madeira" },
      MAIPO: { en: "maipo", fr: "maipo", it: "maipo", de: "maipo" },
      MARCHES: { en: "marches", fr: "marches", it: "marche", de: "marken" },
      MARGARET_RIVER: {
        en: "margaret-river",
        fr: "margaret-river",
        it: "margaret-river",
        de: "margaret-river",
      },
      MARIE_GALANTE: {
        en: "marie-galante",
        fr: "marie-galante",
        it: "marie-galante",
        de: "marie-galante",
      },
      MARLBOROUGH: { en: "marlborough", fr: "marlborough", it: "marlborough", de: "marlborough" },
      MARTINIQUE: { en: "martinique", fr: "martinique", it: "martinica", de: "martinique" },
      MAURICE: { en: "mauritius", fr: "maurice", it: "mauritius", de: "mauritius" },
      MCLAREN_VALE: {
        en: "mclaren-vale",
        fr: "mclaren-vale",
        it: "mclaren-vale",
        de: "mclaren-vale",
      },
      MEKNES: { en: "meknes", fr: "meknes", it: "meknes", de: "meknes" },
      MENDOZA: { en: "mendoza", fr: "mendoza", it: "mendoza", de: "mendoza" },
      MEXIQUE: { en: "mexico", fr: "mexique", it: "messico", de: "mexiko" },
      MOSEL_SAAR: { en: "mosel-saar", fr: "mosel-saar", it: "mosella-saar", de: "mosel-saar" },
      MOSELLE: { en: "moselle", fr: "moselle", it: "mosella", de: "moselle" },
      MURCIE: { en: "murcia", fr: "murcie", it: "murcia", de: "murcia" },
      NAHE: { en: "nahe", fr: "nahe", it: "nahe", de: "nahe" },
      NAPA_VALLEY: { en: "napa-valley", fr: "napa-valley", it: "napa-valley", de: "napa-valley" },
      NAVARRE: { en: "navarre", fr: "navarre", it: "navarra", de: "navarra" },
      NELSON: { en: "nelson", fr: "nelson", it: "nelson", de: "nelson" },
      NEPAL: { en: "nepal", fr: "nepal", it: "nepal", de: "nepal" },
      NEUCHATEL: { en: "neuchatel", fr: "neuchatel", it: "neuchatel", de: "neuenburg" },
      NEW_YORK: { en: "new-york", fr: "new-york", it: "new-york", de: "new-york" },
      NICARAGUA: { en: "nicaragua", fr: "nicaragua", it: "nicaragua", de: "nicaragua" },
      NORD: { en: "north", fr: "nord", it: "nord", de: "norden" },
      NORMANDIE: { en: "normandy", fr: "normandie", it: "normandia", de: "normandie" },
      NOUVELLE_ANGLETERRE: {
        en: "new-england",
        fr: "nouvelle-angleterre",
        it: "nuova-inghilterra",
        de: "neuengland",
      },
      NOUVELLE_ZELANDE: {
        en: "new-zealand",
        fr: "nouvelle-zelande",
        it: "nuova-zelanda",
        de: "neuseeland",
      },
      OAXACA: { en: "oaxaca", fr: "oaxaca", it: "oaxaca", de: "oaxaca" },
      OKINAWA: { en: "okinawa", fr: "okinawa", it: "okinawa", de: "okinawa" },
      OMBRIE: { en: "umbria", fr: "ombrie", it: "umbria", de: "umbrien" },
      OREGON: { en: "oregon", fr: "oregon", it: "oregon", de: "oregon" },
      PANAMA: { en: "panama", fr: "panama", it: "panamá", de: "panama" },
      PATAGONIE: { en: "patagonia", fr: "patagonie", it: "patagonia", de: "patagonien" },
      PAYS_DE_BADE: {
        en: "baden",
        fr: "pays-de-bade",
        it: "baden-wurttemberg",
        de: "baden-wurttemberg",
      },
      PELOPONNESE: { en: "peloponnese", fr: "peloponnese", it: "peloponneso", de: "peloponnes" },
      PENNSYLVANIE: {
        en: "pennsylvania",
        fr: "pennsylvanie",
        it: "pennsylvania",
        de: "pennsylvania",
      },
      PEROU: { en: "peru", fr: "perou", it: "perù", de: "peru" },
      PFALZ: { en: "pfalz", fr: "pfalz", it: "pfalz", de: "pfalz" },
      PIEMONT: { en: "piedmont", fr: "piemont", it: "piemonte", de: "piemont" },
      POLOGNE: { en: "poland", fr: "pologne", it: "polonia", de: "polen" },
      PORTO_RICO: { en: "puerto-rico", fr: "porto-rico", it: "porto-rico", de: "puerto-rico" },
      PORTUGAL: { en: "portugal", fr: "portugal", it: "portogallo", de: "portugal" },
      PRIMORSKI: { en: "primorski", fr: "primorski", it: "primorski", de: "primorski" },
      PROVENCE: { en: "provence", fr: "provence", it: "provenza", de: "provence" },
      REPUBLIQUE_DOMINICAINE: {
        en: "dominican-republic",
        fr: "republique-dominicaine",
        it: "repubblica-dominicana",
        de: "dominikanische-republik",
      },
      REPUBLIQUE_TCHEQUE: {
        en: "czech-republic",
        fr: "republique-tcheque",
        it: "repubblica-ceca",
        de: "tschechische-republik",
      },
      RHEINGAU: { en: "rheingau", fr: "rheingau", it: "rheingau", de: "rheingau" },
      RHEINHESSEN: { en: "rheinhessen", fr: "rheinhessen", it: "rheinhessen", de: "rheinhessen" },
      RHONE_ALPES: { en: "rhone-alpes", fr: "rhone-alpes", it: "rodano-alpi", de: "rhone-alpes" },
      RIBERA_DEL_DUERO: {
        en: "ribera-del-duero",
        fr: "ribera-del-duero",
        it: "ribera-del-duero",
        de: "ribera-del-duero",
      },
      RIO_NEGRO: { en: "rio-negro", fr: "rio-negro", it: "rio-negro", de: "rio-negro" },
      RIOJA: { en: "rioja", fr: "rioja", it: "rioja", de: "rioja" },
      ROUSSILLON: { en: "roussillon", fr: "roussillon", it: "roussillon", de: "roussillon" },
      RUSSIE: { en: "russia", fr: "russie", it: "russia", de: "russland" },
      SAINT_MARTIN: {
        en: "saint-martin",
        fr: "saint-martin",
        it: "saint-martin",
        de: "saint-martin",
      },
      SAINTE_LUCIE: {
        en: "saint-lucia",
        fr: "sainte-lucie",
        it: "santa-lucia",
        de: "saint-lucia",
      },
      SAN_JUAN: { en: "san-juan", fr: "san-juan", it: "san-juan", de: "san-juan" },
      SANTORIN: { en: "santorini", fr: "santorin", it: "santorini", de: "santorin" },
      SARDAIGNE: { en: "sardinia", fr: "sardaigne", it: "sardegna", de: "sardinien" },
      SAVOIE: { en: "savoie", fr: "savoie", it: "savoia", de: "savoie" },
      SEYCHELLES: { en: "seychelles", fr: "seychelles", it: "seychelles", de: "seychellen" },
      SICILE: { en: "sicily", fr: "sicile", it: "sicilia", de: "sizilien" },
      SLOVAQUIE: { en: "slovakia", fr: "slovaquie", it: "slovacchia", de: "slowakei" },
      SONOMA: { en: "sonoma", fr: "sonoma", it: "sonoma", de: "sonoma" },
      SOUTH_AUSTRALIA: {
        en: "south-australia",
        fr: "south-australia",
        it: "australia-meridionale",
        de: "sudaustralien",
      },
      SPEYSIDE: { en: "speyside", fr: "speyside", it: "speyside", de: "speyside" },
      SRI_LANKA: { en: "sri-lanka", fr: "sri-lanka", it: "sri-lanka", de: "sri-lanka" },
      STELLENBOSCH: {
        en: "stellenbosch",
        fr: "stellenbosch",
        it: "stellenbosch",
        de: "stellenbosch",
      },
      SUD_OUEST: { en: "southwest", fr: "sud-ouest", it: "sud-ouest", de: "sudwesten" },
      SUEDE: { en: "sweden", fr: "suede", it: "svezia", de: "schweden" },
      SWARTLAND: { en: "swartland", fr: "swartland", it: "swartland", de: "swartland" },
      TAHITI: { en: "tahiti", fr: "tahiti", it: "tahiti", de: "tahiti" },
      TAIWAN: { en: "taiwan", fr: "taiwan", it: "taiwan", de: "taiwan" },
      TASMANIE: { en: "tasmania", fr: "tasmanie", it: "tasmania", de: "tasmanien" },
      TCHECOSLOVAQUIE: {
        en: "czechoslovakia",
        fr: "tchecoslovaquie",
        it: "cecoslovacchia",
        de: "tschechoslowakei",
      },
      TENERIFE: { en: "tenerife", fr: "tenerife", it: "tenerife", de: "teneriffa" },
      TENNESSEE: { en: "tennessee", fr: "tennessee", it: "tennessee", de: "tennessee" },
      TESSIN: { en: "ticino", fr: "tessin", it: "ticino", de: "tessin" },
      TEXAS: { en: "texas", fr: "texas", it: "texas", de: "texas" },
      TOKAJ: { en: "tokaj", fr: "tokaj", it: "tokaj", de: "tokaj" },
      TORO: { en: "toro", fr: "toro", it: "toro", de: "toro" },
      TOSCANE: { en: "tuscany", fr: "toscane", it: "toscana", de: "toskana" },
      TOTORI: { en: "tottori", fr: "totori", it: "tottori", de: "tottori" },
      TRENTIN_HAUT_ADIGE: {
        en: "trentino-alto-adige",
        fr: "trentin-haut-adige",
        it: "trentino-alto-adige",
        de: "trentino-sudtirol",
      },
      TRINITE_ET_TOBAGO: {
        en: "trinidad-and-tobago",
        fr: "trinite-et-tobago",
        it: "trinidad-e-tobago",
        de: "trinidad-und-tobago",
      },
      UCO: { en: "uco", fr: "uco", it: "uco", de: "uco" },
      URSS: { en: "ussr", fr: "urss", it: "urss", de: "udssr" },
      URUGUAY: { en: "uruguay", fr: "uruguay", it: "uruguay", de: "uruguay" },
      VALAIS: { en: "valais", fr: "valais", it: "vallese", de: "wallis" },
      VALENCE: { en: "valencia", fr: "valence", it: "valencia", de: "valencia" },
      VALLEE_D_AOSTE: {
        en: "aosta-valley",
        fr: "vallee-d-aoste",
        it: "valle-d'aosta",
        de: "aostatal",
      },
      VALLEE_DE_LA_LOIRE: {
        en: "loire-valley",
        fr: "vallee-de-la-loire",
        it: "valle-della-loira",
        de: "loiretal",
      },
      VALLEE_DU_DOURO: {
        en: "douro-valley",
        fr: "vallee-du-douro",
        it: "valle-del-douro",
        de: "douro-tal",
      },
      VALLEE_DU_RHONE: {
        en: "rhone-valley",
        fr: "vallee-du-rhone",
        it: "valle-del-rodano",
        de: "rhonetal",
      },
      VENETIE: { en: "veneto", fr: "venetie", it: "veneto", de: "venetien" },
      VENEZUELA: { en: "venezuela", fr: "venezuela", it: "venezuela", de: "venezuela" },
      VICTORIA: { en: "victoria", fr: "victoria", it: "victoria", de: "victoria" },
      VINHO_VERDE: { en: "vinho-verde", fr: "vinho-verde", it: "vinho-verde", de: "vinho-verde" },
      VIRGINIE: { en: "virginia", fr: "virginie", it: "virginia", de: "virginia" },
      WAIRAPAPA: { en: "wairapapa", fr: "wairapapa", it: "wairapapa", de: "wairapapa" },
      WALLA_WALLA_VALLEY: {
        en: "walla-walla-valley",
        fr: "walla-walla-valley",
        it: "valle-di-walla-walla",
        de: "walla-walla-valley",
      },
      WASHINGTON: { en: "washington", fr: "washington", it: "washington", de: "washington" },
      WESTERN_AUSTRALIA: {
        en: "western-australia",
        fr: "western-australia",
        it: "australia-occidentale",
        de: "westaustralien",
      },
      WESTERN_CAPE: {
        en: "western-cape",
        fr: "western-cape",
        it: "capo-occidentale",
        de: "westkap",
      },
      YAMANASHI: { en: "yamanashi", fr: "yamanashi", it: "yamanashi", de: "yamanashi" },
      YILAN_COUNTY: {
        en: "yilan-county",
        fr: "yilan-county",
        it: "contea-di-yilan",
        de: "yilan-county",
      },
      YUNNAN: { en: "yunnan", fr: "yunnan", it: "yunnan", de: "yunnan" },
    },
    type: "enum",
    priority: 2,
  },
  subregion: {
    translatedKey: {
      en: "appellation",
      fr: "appellation",
      it: "appellation",
      de: "appellation",
    },
    type: "transform",
    priority: 3,
  },
  color: {
    translatedKey: {
      en: "color",
      fr: "couleur",
      it: "colore",
      de: "farbe",
    },
    translatedValues: {
      AMBER: { en: "brown", fr: "ambre", it: "ambrato", de: "braun" },
      WHITE: { en: "white", fr: "blanc", it: "bianco", de: "weiss" },
      SPARKLING_WHITE: {
        en: "sparkling",
        fr: "blanc-effervescent",
        it: "bianco-frizzante",
        de: "schaumwein",
      },
      LIQUOROUS_WHITE: { en: "sweet", fr: "blanc-liquoreux", it: "bianco-dolce", de: "suss" },
      VARIOUS: { en: "misc", fr: "divers", it: "altro", de: "divers" },
      YELLOW: { en: "yellow-liqueur", fr: "jaune", it: "chartreuse-jaune", de: "gelb" },
      ORANGE: { en: "orange", fr: "orange", it: "orange-wine", de: "orange" },
      ROSE: { en: "rose", fr: "rose", it: "rose", de: "rose" },
      SPARKLING_ROSE: {
        en: "sparkling-rose",
        fr: "rose-effervescent",
        it: "rose-frizzante",
        de: "schaumwein-rose",
      },
      RED: { en: "red", fr: "rouge", it: "rosso", de: "rot" },
      SPARKLING_RED: {
        en: "sparkling-red",
        fr: "rouge-effervescent",
        it: "rosso-frizzante",
        de: "schaumwein-rot",
      },
      GREEN: { en: "green-liqueur", fr: "vert", it: "chartreuse-verte", de: "grun" },
      DEMI_DRY_WHITE: {
        en: "demi-sec",
        fr: "blanc-demi-sec",
        it: "bianco-demi-sec",
        de: "halbtrocken",
      },
      DRY_WHITE: {
        en: "sec",
        fr: "blanc-sec",
        it: "bianco-sec",
        de: "weiss-trocken",
      },
      INDIFFERENT: {
        en: "indifferent",
        fr: "indifferent",
        it: "indifferent",
        de: "indifferent",
      },
    },
    type: "enum",
    priority: 4,
  },
  vintage: {
    translatedKey: {
      en: "vintage",
      fr: "millesime",
      it: "annata",
      de: "jahrgang",
    },
    type: "identical",
    priority: 5,
  },
  bottleSize: {
    translatedKey: {
      en: "bottle-size",
      fr: "format",
      it: "formato",
      de: "format",
    },
    translatedValues: {
      BOUTEILLE: { en: "bottle", fr: "bouteille", it: "bottiglia", de: "flasche" },
      DEMI_BOUTEILLE: {
        en: "half-bottle",
        fr: "demi-bouteille",
        it: "mezza-bottiglia",
        de: "demi-flasche",
      },
      DOUBLE_MAGNUM: {
        en: "double-magnum",
        fr: "double-magnum",
        it: "jeroboam-(3-L)",
        de: "doppel-magnum",
      },
      IMPERIALE: { en: "imperiale", fr: "imperiale", it: "imperiale", de: "imperiale" },
      MAGNUM: { en: "magnum", fr: "magnum", it: "magnum", de: "magnum" },
      MATHUSALEM: { en: "methuselah", fr: "mathusalem", it: "mathusalem", de: "methusalem" },
      BALTHAZAR: { en: "balthazar", fr: "balthazar", it: "balthazar", de: "balthazar" },
      CHOPINE: { en: "chopine", fr: "chopine", it: "chopine", de: "chopine" },
      CLAVELIN: { en: "clavelin", fr: "clavelin", it: "clavelin", de: "clavelin" },
      FILLETTE: { en: "fillette", fr: "fillette", it: "fillette", de: "fillette" },
      FLACON: { en: "flacon", fr: "flacon", it: "bottiglia-", de: "flasche-" },
      FORMAT_50_CL: {
        en: "format-50-cl",
        fr: "format-50-cl",
        it: "format-50-cl",
        de: "format-50-cl",
      },
      INCONNU: { en: "other-format", fr: "inconnu", it: "altro-formato", de: "anderes-format" },
      JEROBOAM: { en: "jeroboam", fr: "jeroboam", it: "jeroboam", de: "jeroboam" },
      LITRE: { en: "litre", fr: "litre", it: "litro", de: "liter" },
      MELCHIOR: { en: "melchior", fr: "melchior", it: "melchior", de: "salomon" },
      NABUCHODONOSOR: {
        en: "nebuchadnezzar",
        fr: "nabuchodonosor",
        it: "nabuchodonosor",
        de: "nebukadnezar",
      },
      POT: { en: "pot", fr: "pot", it: "pot-lyonnais", de: "pot" },
      REHOBOAM: { en: "rehoboam", fr: "rehoboam", it: "rehoboam", de: "rehoboam" },
      SALMANAZAR: { en: "salmanazar", fr: "salmanazar", it: "salmanazar", de: "salmanazar" },
    },
    type: "enum",
    priority: 6,
  },
  ownerName: {
    translatedKey: {
      en: "owner",
      fr: "proprietaire",
      it: "proprietario",
      de: "eigentümer",
    },
    type: "transform",
    priority: 7,
  },
  liquidLevels: {
    translatedKey: {
      en: "level",
      fr: "niveau",
      it: "livello",
      de: "fullstand",
    },
    translatedValues: {
      A_10_CM: { en: "10cm", fr: "a-10-cm", it: "10-cm", de: "10-cm" },
      A_2_5_CM: { en: "a-25-cm", fr: "a-25-cm", it: "a-25-cm", de: "a-25-cm" },
      A_2_CM: { en: "2cm", fr: "a-2-cm", it: "2-cm", de: "2-cm" },
      A_3_5_CM: { en: "a-35-cm", fr: "a-35-cm", it: "a-35-cm", de: "a-35-cm" },
      A_3_CM: { en: "3cm", fr: "a-3-cm", it: "3-cm", de: "3-cm" },
      A_4_5_CM: { en: "a-45-cm", fr: "a-45-cm", it: "a-45-cm", de: "a-45-cm" },
      A_4_CM: { en: "4cm", fr: "a-4-cm", it: "4-cm", de: "4-cm" },
      A_5_5_CM: { en: "a-55-cm", fr: "a-55-cm", it: "a-55-cm", de: "a-55-cm" },
      A_5_CM: { en: "5cm", fr: "a-5-cm", it: "5-cm", de: "5-cm" },
      A_6_5_CM: { en: "a-45-cm", fr: "a-45-cm", it: "a-45-cm", de: "a-45-cm" },
      A_6_CM: { en: "6cm", fr: "a-6-cm", it: "6-cm", de: "6-cm" },
      A_7_CM: { en: "7cm", fr: "a-7-cm", it: "7-cm", de: "7-cm" },
      A_8_CM: { en: "8cm", fr: "a-8-cm", it: "8-cm", de: "8-cm" },
      A_9_CM: { en: "9cm", fr: "a-9-cm", it: "9-cm", de: "9-cm" },
      BASE_GOULOT: {
        en: "base-of-neck",
        fr: "base-goulot",
        it: "a-livello-del-collo",
        de: "fullstand",
      },
      BASSE_EPAULE: {
        en: "low-shoulder",
        fr: "basse-epaule",
        it: "spalla-bassa",
        de: "low-shoulder",
      },
      ENTRE_2_ET_4_CM: {
        en: "between-2-and-4cm",
        fr: "entre-2-et-4-cm",
        it: "tra-i-2-4-cm",
        de: "zwischen-zwei-und-vier-zentimetern",
      },
      ENTRE_4_ET_6_CM: {
        en: "between-4-and-6cm",
        fr: "entre-4-et-6-cm",
        it: "tra-i-4-6-cm",
        de: "zwischen-vier-und-sechs-zentimetern",
      },
      HAUTE_EPAULE: {
        en: "upper-shoulder",
        fr: "haute-epaule",
        it: "sulla-spalla",
        de: "upper-shoulder",
      },
      LEGEREMENT_BAS: {
        en: "top-shoulder",
        fr: "legerement-bas",
        it: "sopra-la-spalla-della-bottiglia",
        de: "top-shoulder",
      },
      MI_EPAULE: { en: "mid-shoulder", fr: "mi-epaule", it: "meta-spalla", de: "mid-shoulder" },
      MOINS_DE_2_CM: {
        en: "less-than-2cm",
        fr: "moins-de-2-cm",
        it: "meno-di-2-cm",
        de: "weniger-als-zwei-zentimeter",
      },
      NORMAL: { en: "into-neck", fr: "normal", it: "normale", de: "normal" },
      TRES_LEGEREMENT_BAS: {
        en: "high-shoulder",
        fr: "tres-legerement-bas",
        it: "leggermente-basso",
        de: "high-shoulder",
      },
      VIDANGE: {
        en: "withdrawn",
        fr: "vidange",
        it: "svuotamento-(causa-colatura)",
        de: "loschen",
      },
      BAS: { en: "low", fr: "bas", it: "basso", de: "Niedrig" },
      PLUS_DE_10_CM: {
        en: "more-than-10cm",
        fr: "plus_de_10_cm",
        it: "piu-di-10-cm",
        de: "mehr-als-zehn-zentimeter",
      },
      PLUS_DE_6_CM: {
        en: "more-than-6cm",
        fr: "plus_de_6_cm",
        it: "piu-di-6-cm",
        de: "mehr-als-sechs-zentimeter",
      },
    },
    type: "enum",
    priority: 8,
  },
  bottleObservations: {
    translatedKey: {
      en: "bottle-condition",
      fr: "etiquette",
      it: "etichetta",
      de: "etikett",
    },
    translatedValues: {
      CAPSULE_NORMALE: {
        en: "normale-capsule",
        fr: "capsule-normale",
        it: "capsula-normale",
        de: "normale-kapsel",
      },
      CAPS_PLASTIQUE_ABIMEE: {
        en: "damaged-plastic-capsule",
        fr: "caps-plastique-abimee",
        it: "capsula-in-plastica-rovinata",
        de: "plastik-kapsel-beschädigt",
      },
      CIRE_ABIMEE: {
        en: "damaged-wax",
        fr: "cire-abimee",
        it: "cera-rovinata",
        de: "wachs-beschädigt",
      },
      CIRE_LEG_ABIMEE: {
        en: "slightly-damaged-wax",
        fr: "cire-leg-abimee",
        it: "cera-leggermente-rovinata",
        de: "wachs-leicht-beschädigt",
      },
      COLL_ABIMEE: {
        en: "damaged-vintage-slip",
        fr: "coll-abimee",
        it: "etich.-sul-collo-rovinata",
        de: "halsetikett-beschädigt",
      },
      COLL_GRIFFEE: {
        en: "scuffed-vintage-slip",
        fr: "coll-griffee",
        it: "etich.-sul-collo-graffiata",
        de: "halsetikett-verkratzt",
      },
      COLL_MILLESIME_ABSENTE: {
        en: "vintage-slip-missing",
        fr: "coll-millesime-absente",
        it: "etich.-sul-collo-assente",
        de: "jahrgangsetikett-nicht-vorhanden",
      },
      COLL_MILLESIME_LEG_ABIMEE: {
        en: "slightly-damaged-vintage-slip",
        fr: "coll-millesime-leg-abimee",
        it: "etich-sul-collo-leg-rovinata",
        de: "jahrgangsetikett-leicht-abgenutzt",
      },
      COLL_MILLESIME_LEG_GRIFFEE: {
        en: "slightly-scuffed-vintage-slip-",
        fr: "coll-millesime-leg-griffee",
        it: "etich-sul-collo-leg-graffiata",
        de: "jahrgangsetikett-leicht-verkratzt",
      },
      COLL_MILL_TACHEE: {
        en: "stained-vintage-slip",
        fr: "coll-mill-tachee",
        it: "etich-sul-collo-macchiata",
        de: "halsetikett-fleckig",
      },
      COULEUR_TROUBLE: {
        en: "slightly-cloudy",
        fr: "couleur-trouble",
        it: "colore-torbido",
        de: "trübe-farbe",
      },
      ETIQ_DE_SECURITE: {
        en: "security-label",
        fr: "etiq-de-securite",
        it: "etichetta-con-tag-autenticità",
        de: "sicherheitsetikett",
      },
      ETIQ_HUMIDE: {
        en: "damp-affected-label",
        fr: "etiq-humide",
        it: "etichetta-con-segni-di-umidità",
        de: "etikett-feucht",
      },
      ETIQ_LEG_FANEE: {
        en: "slightly-faded-label",
        fr: "etiq-leg-fanee",
        it: "etichetta-sbiadita",
        de: "etikett-leicht-ausgeblichen",
      },
      ETIQ_LISIBLE: {
        en: "legible-label",
        fr: "etiq-lisible",
        it: "etichetta-leggibile",
        de: "etikett-lesbar",
      },
      ETIQ_SALIE_DE_COLLE: {
        en: "glue-stained-label",
        fr: "etiq-salie-de-colle",
        it: "tracce-di-colla-sulletichetta",
        de: "etikett-durch-klebstoff-verschmutzt",
      },
      ETIQ_TRES_HUMIDE: {
        en: "very-damp-affected-label",
        fr: "etiq-tres-humide",
        it: "etichetta-ammuffita",
        de: "etikett-sehr-feucht",
      },
      BCH_ESTAMPE: {
        en: "vintage-on-cork",
        fr: "bch-estampe",
        it: "tappo-con-incisione",
        de: "korken-gestanzt",
      },
      BCH_FAIBLE: { en: "weak-cork", fr: "bch-faible", it: "tappo-debole", de: "korken-fragil" },
      BCH_LEG_DESCENDU: {
        en: "cork-slightly-down",
        fr: "bch-leg-descendu",
        it: "tappo-che-inizia-leggermente-a-cadere",
        de: "korken-leicht-eingedruckt",
      },
      BCH_LEG_ENFONCE: {
        en: "slightly-pushed-cork",
        fr: "bch-leg-enfonce",
        it: "tappo-non-totalmente-ermetico",
        de: "korken-leicht-eingedrückt",
      },
      BTE_COULEUSE: {
        en: "signs-of-seepage",
        fr: "bte-couleuse",
        it: "segni-di-perdita",
        de: "flasche-undicht",
      },
      BTE_LEG_COULEUSE: {
        en: "light-signs-of-seepage",
        fr: "bte-leg-couleuse",
        it: "bottiglia-con-lievi-tracce-di-perdita",
        de: "leichte-spuren-von-feuchtigkeit",
      },
      BTE_LEGERE: {
        en: "light-bottle",
        fr: "bte-legere",
        it: "bottiglia-leggera",
        de: "leichte-flasche",
      },
      BTE_RECONDITIONNEE: {
        en: "reconditioned-bottle",
        fr: "bte-reconditionnee",
        it: "bottiglia-ricolmata",
        de: "rekonditionierte-flasche",
      },
      CAPS_CONGE: { en: "crd-capsule", fr: "caps-conge", it: "crd", de: "crd-kapsel" },
      CAPS_NEUTRE: {
        en: "neutral-capsule",
        fr: "caps-neutre",
        it: "capsula-neutra",
        de: "neutrale-kapsel",
      },
      ETIQ_VERNIE: {
        en: "varnished-label",
        fr: "etiq-vernie",
        it: "etichetta-con-segni-di-vernice",
        de: "etikett-lackiert",
      },
      BCH_DESCENDU: {
        en: "cork-down",
        fr: "bch-descendu",
        it: "tappo-che-inizia-a-cadere",
        de: "korken-eingedruckt",
      },
      BCH_ENFONCE: {
        en: "slightly-pushed-cork",
        fr: "bch-leg-enfonce",
        it: "tappo-non-totalmente-ermetico",
        de: "korken-leicht-eingedruckt",
      },
      BCH_LEG_SOULEVE: {
        en: "slightly-raised-cork",
        fr: "bch-leg-souleve",
        it: "tappo-leggermente-rigonfio",
        de: "korken-leicht-herausgedruckt",
      },
      BTE_CIREE: {
        en: "wax-bottle",
        fr: "bte-ciree",
        it: "bottiglia-sigillata-da-una-capsula-in-cera",
        de: "flasche-mit-wachs-kapsel",
      },
      CAPS_ABIMEE: {
        en: "damaged-capsule",
        fr: "caps-abimee",
        it: "capsula-rovinata",
        de: "kapsel-beschadigt",
      },
      CAPS_ABSENTE: {
        en: "capsule-missing",
        fr: "caps-absente",
        it: "capsula-mancante",
        de: "kapsel-nicht-vorhanden",
      },
      CAPS_CIRE_ABIMEE: {
        en: "damaged-wax-capsule",
        fr: "caps-cire-abimee",
        it: "capsula-in-cera-rovinata",
        de: "wachskapsel-beschadigt",
      },
      CAPS_CIRE_LEG_ABIMEE: {
        en: "slightly-damaged-wax-capsule",
        fr: "caps-cire-leg-abimee",
        it: "capsula-in-cera-leggermente-rovinata",
        de: "wachs-kapsel-leicht-beschadigt",
      },
      CAPS_CIRE: { en: "wax-capsule", fr: "caps-cire", it: "capsula-in-cera", de: "wachs-kapsel" },
      CAPS_CORRODEE: {
        en: "corroded-capsule",
        fr: "caps-corrodee",
        it: "capsula-deteriorata",
        de: "kapsel-korrodiert",
      },
      CAPS_DECOUPEE: {
        en: "cut-capsule",
        fr: "caps-decoupee",
        it: "capsula-tagliata",
        de: "kapsel-abgeschnitten",
      },
      CAPS_DESOLIDARISEE: {
        en: "dissociated-capsule",
        fr: "caps-desolidarisee",
        it: "capsula-distaccato",
        de: "kapsel-losgelost",
      },
      CAPS_GRIFFEE: {
        en: "scuffed-capsule",
        fr: "caps-griffee",
        it: "capsula-graffiata",
        de: "kapsel-verkratzt",
      },
      CAPS_LEG_ABIMEE: {
        en: "slightly-damaged-capsule",
        fr: "caps-leg-abimee",
        it: "capsula-leggermente-rovinata",
        de: "kapsel-leicht-beschadigt",
      },
      CAPS_LEG_CORRODEE: {
        en: "slightly-corroded-capsule",
        fr: "caps-leg-corrodee",
        it: "capsula-leggermente-deteriorata",
        de: "kapsel-leicht-korrodiert",
      },
      CAPS_LEG_GRIFFEE: {
        en: "slightly-scuffed-capsule",
        fr: "caps-leg-griffee",
        it: "capsula-leggermente-graffiata",
        de: "kapsel-leicht-verkratzt",
      },
      CAPS_PLASTIQUE: {
        en: "plastic-capsule",
        fr: "caps-plastique",
        it: "capsula-in-plastica",
        de: "plastik-kapsel",
      },
      CAPS_SALE: {
        en: "bin-soiled-capsule",
        fr: "caps-sale",
        it: "capsula-sporca",
        de: "kapsel-schmutzig",
      },
      CAPS_TACHEE: {
        en: "stained-capsule",
        fr: "caps-tachee",
        it: "capsula-macchiata",
        de: "kapsel-fleckig",
      },
      CAPS_TRES_ABIMEE: {
        en: "very-damaged-capsule",
        fr: "caps-tres-abimee",
        it: "capsula-molto-rovinata",
        de: "kapsel-stark-beschadigt",
      },
      COFFRET_D_ORIGINE_ABIME: {
        en: "original-box-damaged",
        fr: "coffret-dorigine-abime",
        it: "cofanetto/astuccio-rovinato",
        de: "originalverpackung-beschadigt",
      },
      COFFRET_D_ORIGINE_LEGEREMENT_ABIME: {
        en: "original-box-slightly-damaged",
        fr: "coffret-dorigine-legerement-abime",
        it: "cofanetto/astuccio-leggermente-rovinato",
        de: "originalverpackung-leicht-beschadigt",
      },
      COFFRET_D_ORIGINE_TRES_LEGEREMENT_ABIME: {
        en: "original-box-very-slightly-damaged",
        fr: "coffret-dorigine-tres-legerement-abime",
        it: "cofanetto/astuccio-appena-rovinato",
        de: "originalverpackung-sehr-leicht-beschadigt",
      },
      ETIQ_ABIMEE: {
        en: "damaged-label",
        fr: "etiq-abimee",
        it: "etichetta-rovinata",
        de: "etikett-beschadigt",
      },
      ETIQ_DECHIREE: {
        en: "torn-label",
        fr: "etiq-dechiree",
        it: "etichetta-strappata",
        de: "etikett-eingerissen",
      },
      ETIQ_DECOLLEE: {
        en: "peeled-off-label",
        fr: "etiq-decollee",
        it: "etichetta-staccata",
        de: "etikett-abgelost",
      },
      ETIQ_DIFFICILEMENT_LISIBLE: {
        en: "hardly-legible-label",
        fr: "etiq-difficilement-lisible",
        it: "etichetta-appena-leggibile",
        de: "etikett-schwer-lesbar",
      },
      ETIQ_EMPOUSSIEREE: {
        en: "dusty-label",
        fr: "etiq-empoussieree",
        it: "etichetta-piena-di-polvere",
        de: "etikett-staubig",
      },
      ETIQ_FANEE: {
        en: "slightly-faded-label",
        fr: "etiq-fanee",
        it: "etichetta-sbiadita",
        de: "etikett-leicht-ausgeblichen",
      },
      ETIQ_FILMEE: {
        en: "label-covered-with-film",
        fr: "etiq-filmee",
        it: "pellicola-protettiva-intorno-alletichetta",
        de: "etikett-mit-klebefilm-versehen",
      },
      ETIQ_FRAGILE: {
        en: "fragile-label",
        fr: "etiq-fragile",
        it: "etichetta-fragile",
        de: "etikett-fragil",
      },
      ETIQ_FRIABLE: {
        en: "crisp-label",
        fr: "etiq-friable",
        it: "etichetta-che-si-sgretola",
        de: "etikett-bruchig",
      },
      ETIQ_FRIPEE: {
        en: "wrinkled-label",
        fr: "etiq-fripee",
        it: "etichetta-stropicciata",
        de: "etikett-verknittert",
      },
      ETIQ_GRIFFEE: {
        en: "scuffed-label",
        fr: "etiq-griffee",
        it: "etichetta-graffiata",
        de: "spuren-von-cutter",
      },
      ETIQ_ILLISIBLE: {
        en: "non-legible-label",
        fr: "etiq-illisible",
        it: "etichetta-illeggibile",
        de: "etikett-unleserlich",
      },
      ETIQ_JAUNIE: {
        en: "yellowed-label",
        fr: "etiq-jaunie",
        it: "etichetta-ingiallita",
        de: "etikett-vergilbt",
      },
      ETIQ_LAMBEAUX: {
        en: "fragments-of-label",
        fr: "etiq-lambeaux",
        it: "etichetta-sgretolata",
        de: "etikett-zerfetzt",
      },
      ETIQ_LEG_ABIMEE: {
        en: "slightly-bin-soiled-label",
        fr: "etiq-leg-abimee",
        it: "etichetta-leggermente-rovinata",
        de: "etikett-leicht-abgenutzt",
      },
      ETIQ_LEG_DECHIREE: {
        en: "slightly-torn-label",
        fr: "etiq-leg-dechiree",
        it: "etichetta-leggermente-strappata",
        de: "etikett-leicht-eingerissen",
      },
      ETIQ_LEG_DECOLLEE: {
        en: "slightly-peeled-off-label",
        fr: "etiq-leg-decollee",
        it: "etichetta-leggermente-scollata",
        de: "etikett-leicht-abgelost",
      },
      ETIQ_LEG_FRIPEE: {
        en: "slightly-wrinkled-label",
        fr: "etiq-leg-fripee",
        it: "etichetta-leggermente-stropicciata",
        de: "etikett-leicht-verknittert",
      },
      ETIQ_LEG_GRIFFEE: {
        en: "slightly-scuffed-label",
        fr: "etiq-leg-griffee",
        it: "etichetta-leggermente-graffiata",
        de: "etikett-leicht-verkratzt",
      },
      ETIQ_LEG_HUMIDE: {
        en: "slightly-damp-affected-label",
        fr: "etiq-leg-humide",
        it: "etichetta-con-segni-di-umidita",
        de: "etikett-leicht-feucht",
      },
      ETIQ_LEG_MARQUEE: {
        en: "slightly-marked-label",
        fr: "etiq-leg-marquee",
        it: "etichetta-un-po-macchiata",
        de: "etikett-leicht-verschmutzt",
      },
      ETIQ_LEG_PIQUEE: {
        en: "slightly-pricked-label",
        fr: "etiq-leg-piquee",
        it: "etichetta-leggermente-ammuffita",
        de: "etikett-leicht-fleckig",
      },
      ETIQ_LEG_PLISSEE: {
        en: "slightly-folded-label",
        fr: "etiq-leg-plissee",
        it: "etichetta-leggermente-piegata",
        de: "etikett-leicht-verknickt",
      },
      ETIQ_LEG_SALE: {
        en: "slightly-dirty-label",
        fr: "etiq-leg-sale",
        it: "etichetta-leggermente-sporca",
        de: "etikett-leicht-verschmutzt",
      },
      ETIQ_LEG_TACHEE: {
        en: "slightly-stained-label",
        fr: "etiq-leg-tachee",
        it: "etichetta-un-po-macchiata",
        de: "etikett-leicht-verschmutzt",
      },
      ETIQ_LEG_USEE: {
        en: "slightly-worn-label",
        fr: "etiq-leg-usee",
        it: "etichetta-leggermente-danneggiata",
        de: "etikett-leicht-abgenutzt",
      },
      ETIQ_MARQUEE: {
        en: "marked-label",
        fr: "etiq-marquee",
        it: "etichetta-macchiata",
        de: "etikett-markiert",
      },
      ETIQ_PIQUEE: {
        en: "pricked-label",
        fr: "etiq-piquee",
        it: "etichetta-ammuffita",
        de: "etikett-sehr-feucht",
      },
      ETIQ_PLISSEE: {
        en: "folded-label",
        fr: "etiq-plissee",
        it: "etichetta-piegata",
        de: "etikett-verknickt",
      },
      ETIQ_QUASI_ILLISIBLE: {
        en: "not-legible-label",
        fr: "etiq-quasi-illisible",
        it: "etichetta-quasi-totalmente-illeggibile",
        de: "etikett-quasi-unleserlich",
      },
      ETIQ_RECOLLEE: {
        en: "glued-label",
        fr: "etiq-recollee",
        it: "etichetta-rincollata",
        de: "etikett-wieder-angeklebt",
      },
      ETIQ_SALE: {
        en: "soiled-label",
        fr: "etiq-sale",
        it: "etichetta-sporca",
        de: "etikett-schmutzig",
      },
      ETIQ_SALIE_PAR_L_HUMIDITE: {
        en: "damp-stained-label",
        fr: "etiq-salie-par-lhumidite",
        it: "etichetta-rovinata-dallumidita",
        de: "etikett-durch-feuchtigkeit-verschmutzt",
      },
      ETIQ_SCOTCHEE: {
        en: "scotch-taped-label",
        fr: "etiq-scotchee",
        it: "etichetta-incollata-con-lo-scotch",
        de: "etikett-mit-klebefilm-versehen",
      },
      ETIQ_TACHEE: {
        en: "stained-label",
        fr: "etiq-tachee",
        it: "etichetta-macchiata",
        de: "etikett-markiert",
      },
      ETIQ_TRES_ABIMEE: {
        en: "very-bin-soiled-label",
        fr: "etiq-tres-abimee",
        it: "etichetta-molto-rovinata",
        de: "etikett-stark-beschadigt",
      },
      ETIQ_TRES_LEG_ABIMEE: {
        en: "very-slightly-damaged-label",
        fr: "etiq-tres-leg-abimee",
        it: "etichetta-appena-rovinata",
        de: "etikett-ganz-leicht-beschadigt",
      },
      ETIQ_TRES_LEG_DECHIREE: {
        en: "very-slightly-torn-label",
        fr: "etiq-tres-leg-dechiree",
        it: "etichetta-appena-strappata",
        de: "etikett-ganz-leicht-eingerissen",
      },
      ETIQ_TRES_LEG_FRIPEE: {
        en: "very-slightly-wrinkled-label",
        fr: "etiq-tres-leg-fripee",
        it: "etichetta-appena-stropicciata",
        de: "etikett-ganz-leicht-verknittert",
      },
      ETIQ_TRES_LEG_GRIFFEE: {
        en: "very-slightly-scuffed-label",
        fr: "etiq-tres-leg-griffee",
        it: "etichetta-appena-graffiata",
        de: "etikett-ganz-leicht-verkratzt",
      },
      ETIQ_TRES_LEG_MARQUEE: {
        en: "very-slightly-marked-label",
        fr: "etiq-tres-leg-marquee",
        it: "etichetta-appena-macchiata",
        de: "etikett-ganz-leicht-gezeichnet",
      },
      ETIQ_TRES_LEG_TACHEE: {
        en: "very-slightly-stained-label",
        fr: "etiq-tres-leg-tachee",
        it: "etichetta-appena-macchiata",
        de: "etikett-ganz-leicht-gezeichnet",
      },
      ETIQ_TRES_MARQUEE: {
        en: "very-marked-label",
        fr: "etiq-tres-marquee",
        it: "etichetta-molto-macchiata",
        de: "etikett-sehr-verschmutzt",
      },
      ETIQ_TRES_SALE: {
        en: "very-dirty-label",
        fr: "etiq-tres-sale",
        it: "etichetta-con-tracce-di-sporco-in-diversi-punti",
        de: "etikett-sehr-schmutzig",
      },
      ETIQ_TRES_TACHEE: {
        en: "very-stained-label",
        fr: "etiq-tres-tachee",
        it: "etichetta-molto-macchiata",
        de: "etikett-sehr-verschmutzt",
      },
      ETIQ_TRES_USEE: {
        en: "very-faded-label",
        fr: "etiq-tres-usee",
        it: "etichetta-danneggiata-in-diversi-punti",
        de: "etikett-sehr-abgenutzt",
      },
      ETIQ_USEE: {
        en: "faded-label",
        fr: "etiq-usee",
        it: "etichetta-danneggiata",
        de: "etikett-abgenutzt",
      },
      MILL_DIFFICILEMENT_LISIBLE: {
        en: "hardly-legible-vintage",
        fr: "mill-difficilement-lisible",
        it: "annata-appena-leggibile",
        de: "jahrgang-schwer-lesbar",
      },
      MILLESIME_ILLISIBLE: {
        en: "vintage-not-visible",
        fr: "millesime-illisible",
        it: "annata-illeggibile",
        de: "jahrgang-nicht-lesbar",
      },
      MILLESIME_LISIBLE: {
        en: "vintage-visible",
        fr: "millesime-lisible",
        it: "annata-leggibile",
        de: "jahrgang-lesbar",
      },
      MILLESIME_MANUSCRIT: {
        en: "handwritten vintage",
        fr: "millesime-manuscrit",
        it: "annata-scritta-a-mano",
        de: "jahrgang-handgeschrieben",
      },
      MILLESIME_SUR_BOUCHON: {
        en: "vintage-printed-on-cork",
        fr: "millesime-sur-bouchon",
        it: "annata-incisa-sul-tappo	",
        de: "jahrgang-auf-dem-korken",
      },
      NORMALE: { en: "good-appearance", fr: "normale", it: "normale", de: "normal" },
      NUMERO_DE_SERIE_EFFACE: {
        en: "erased-serial-number",
        fr: "numero-de-serie-efface",
        it: "numero-di-serie-cancellato",
        de: "seriennummer-geloscht",
      },
      SANS_ETIQUETTE: { en: "no-label", fr: "", it: "senza-etichetta", de: "ohne-etikett" },
      SANS_MILLESIME: {
        en: "no-vintage",
        fr: "sans-millesime",
        it: "senza-annata",
        de: "ohne-jahrgang",
      },
      TRACES_ANCIENNE_COULURES: {
        en: "old-signs-of-seepage",
        fr: "traces-ancienne-coulures",
        it: "vecchie-tracce-di-perdita",
        de: "alte-spuren-von-feuchtigkeit",
      },
      TRACES_DE_COLLE: {
        en: "glue-stains",
        fr: "traces-de-colle",
        it: "tracce-di-colla",
        de: "spuren-von-klebstoff",
      },
      TRACES_DE_CUTTER: {
        en: "traces-of-cutter",
        fr: "traces-de-cutter",
        it: "etichetta-graffiata",
        de: "spuren-von-cutter",
      },
    },
    type: "enum",
    priority: 9,
  },
  tags: {
    translatedKey: {
      en: "picks",
      fr: "selection",
      it: "selezione",
      de: "auswahl",
    },
    type: "transform",
    priority: 35,
  },
  unitPrice: {
    translatedKey: {
      en: "price-between",
      fr: "prix-entre",
      it: "prezzo-tra",
      de: "preis-spanne",
    },
    type: "identical",
    priority: 11,
  },
  woodenCase: {
    translatedKey: {
      en: "with-wooden-case",
      fr: "avec-caisse-en-bois",
      it: "con-cassetta-in-legno",
      de: "mit-holzkiste",
    },
    type: "boolean",
    priority: 12,
  },
  intensity: {
    translatedKey: {
      en: "intensity",
      fr: "intensite",
      it: "intensita",
      de: "intensität",
    },
    translatedValues: {
      CLASSIQUE: { en: "classic", fr: "classique", it: "classico", de: "klassisch" },
      DOSAGE_CLASSIQUE: {
        en: "classic-dosage",
        fr: "dosage-classique",
        it: "dosaggio-classico",
        de: "klassische-dosage",
      },
      DOUX: { en: "sweet", fr: "doux", it: "dolce", de: "suss" },
      FAIBLE_DOSAGE: {
        en: "low-dosage",
        fr: "faible-dosage",
        it: "basso-dosaggio",
        de: "leichte-dosage",
      },
      FRUITE: { en: "fruity", fr: "fruite", it: "note-fruttate", de: "fruchtig" },
      GOURMAND: {
        en: "voluptuous",
        fr: "gourmand",
        it: "ricco,-ampio,-armonioso",
        de: "geschmeidig",
      },
      LEGER: { en: "light", fr: "leger", it: "leggero", de: "leicht" },
      LIQUOREUX: { en: "dessert-wine", fr: "liquoreux", it: "", de: "dessertwein" },
      MINERAL: { en: "mineral", fr: "mineral", it: "mineral", de: "mineral" },
      MOELLEUX: { en: "sweet", fr: "moelleux", it: "dolce", de: "suss-" },
      ONCTUEUX: { en: "rich", fr: "onctueux", it: "ricco,-morbido", de: "cremig" },
      PUISSANT: { en: "full-bodied", fr: "puissant", it: "intenso", de: "kraftig" },
      SOYEUX: { en: "silky", fr: "soyeux", it: "setoso", de: "seidig" },
      VIF: { en: "crisp", fr: "vif", it: "vivo", de: "frisch,-lebhaft" },
      VIN_MUTE: {
        en: "fortified-wine",
        fr: "vin-mute",
        it: "vino-fortificato/liquoroso",
        de: "gespriteter-wein",
      },
    },
    type: "enum",
    priority: 13,
  },
  mainAroma: {
    translatedKey: {
      en: "dominant-aroma",
      fr: "arome-dominant",
      it: "aroma-dominante",
      de: "dominantes-aroma",
    },
    translatedValues: {
      AGRUMES: { en: "citrus", fr: "agrumes", it: "agrumi", de: "zitrusfruchte" },
      CAFE: { en: "coffee", fr: "cafe", it: "caffe", de: "kaffee" },
      CARAMEL: { en: "caramel", fr: "caramel", it: "caramello", de: "karamell" },
      EPICES: { en: "spices", fr: "epices", it: "spezie", de: "gewurze" },
      EPICES_DOUCES: {
        en: "sweet-spices",
        fr: "epices-douces",
        it: "spezie-dolci",
        de: "susse-gewurze",
      },
      FLEURS_BLANCHES: {
        en: "fleurs-blanches",
        fr: "fleurs-blanches",
        it: "fleurs-blanches",
        de: "fleurs-blanches",
      },
      FLORAL: { en: "floral", fr: "floral", it: "note-floreali", de: "blumig" },
      FRUITE: { en: "fruity", fr: "fruite", it: "note-fruttate", de: "fruchtig" },
      FRUITS_BLANCS: {
        en: "white-fruit",
        fr: "fruits-blancs",
        it: "frutti-bianchi",
        de: "weisse-fruchte",
      },
      FRUITS_CONFITS: {
        en: "candied-fruit",
        fr: "fruits-confits",
        it: "frutta-candita",
        de: "kandierte-fruchte",
      },
      FRUITS_EXOTIQUES: {
        en: "exotic-fruit",
        fr: "fruits-exotiques",
        it: "frutti-tropicali",
        de: "exotische-fruchte",
      },
      FRUITS_JAUNES: {
        en: "yellow-fruit",
        fr: "fruits-jaunes",
        it: "frutti-gialli",
        de: "gelbe-fruchte",
      },
      FRUITS_NOIRS: {
        en: "black-fruit",
        fr: "fruits-noirs",
        it: "frutti-neri",
        de: "schwarze-fruchte",
      },
      FRUITS_ROUGES: {
        en: "red-fruit",
        fr: "fruits-rouges",
        it: "frutti-rossi",
        de: "rote-fruchte",
      },
      FRUITS_SECS: { en: "fruits-secs", fr: "fruits-secs", it: "fruits-secs", de: "fruits-secs" },
      FUME: { en: "smoky", fr: "fume", it: "note-affumicate", de: "rauchig" },
      MIEL: { en: "honey", fr: "miel", it: "miele", de: "honig" },
      MINERAL: { en: "mineral", fr: "mineral", it: "note-minerali", de: "mineralisch" },
      NOIX: { en: "nutty", fr: "noix", it: "noci", de: "nussig" },
      TOURBE: { en: "peat", fr: "tourbe", it: "note-torbate", de: "torf" },
      VANILLE: { en: "vanilla", fr: "vanille", it: "vaniglia", de: "vanille" },
    },
    type: "enum",
    priority: 14,
  },
  tastingOccasion: {
    translatedKey: {
      en: "tasting-occasion",
      fr: "occasion-degustation",
      it: "occasione-degustazione",
      de: "trink-anlass",
    },
    translatedValues: {
      VIN_MEDITATION: {
        en: "meditation-wine",
        fr: "vin-de-meditation",
        it: "vino-da-meditazione",
        de: "meditationswein",
      },
      VIN_GASTRONOMIE: {
        en: "gastronomic-wine",
        fr: "vin-de-gastronomie",
        it: "vino-gastronomico",
        de: "gastronomischer-wein",
      },
      VIN_APERITIF: {
        en: "aperitif-wine",
        fr: "vin-daperitif",
        it: "vino-per-laperitivo",
        de: "aperitif",
      },
    },
    type: "enum",
    priority: 15,
  },
  status: {
    translatedKey: {
      en: "status",
      fr: "statut",
      it: "status",
      de: "status",
    },
    translatedValues: {
      ETOILE_MONTANTE: {
        en: "rising-star",
        fr: "etoile-montante",
        it: "astro-nascente",
        de: "aufgehender-stern",
      },
      ICONE: { en: "icon-wine", fr: "icone", it: "icona", de: "ikone" },
      VIN_COPAINS: {
        en: "enjoy-with-friends",
        fr: "vin-de-copains",
        it: "vino-da-bere-in-compagnia",
        de: "gefalliger-wein",
      },
      VIN_CURIOSITE: {
        en: "wine-for-the-adventurous",
        fr: "vin-de-curiosite",
        it: "vini-insoliti",
        de: "wein-fur-abenteuerlustige",
      },
      VIN_DE_GARDE: {
        en: "vin-de-garde",
        fr: "vin-de-garde",
        it: "vino-da-invecchiamento",
        de: "wein-mit-reifepotenzial",
      },
      VIN_NATURE: { en: "natural", fr: "nature", it: "naturale", de: "natur" },
    },
    type: "enum",
    priority: 16,
  },
  hasBids: {
    translatedKey: {
      en: "with-auction",
      fr: "avec-enchere",
      it: "con-offerte",
      de: "mit-auktion",
    },
    type: "boolean",
    priority: 17,
  },
  hasReservePrice: {
    translatedKey: {
      en: "has-reserve-price",
      fr: "avec-prix-de-reserve",
      it: "con-prezzo-di-riserva",
      de: "mit-mindestpreis",
    },
    type: "boolean",
    priority: 17,
  },
  refundableVat: {
    translatedKey: {
      en: "vat-refundable",
      fr: "tva-recuperable",
      it: "iva-detraibile",
      de: "mwst-erstattbar",
    },
    type: "boolean",
    priority: 18,
  },
  bottleCount: {
    translatedKey: {
      en: "quantity",
      fr: "quantite",
      it: "quantita",
      de: "menge",
    },
    type: "identical",
    priority: 20,
  },
  biologicProfile: {
    translatedKey: {
      en: "biologic-profile",
      fr: "profil-biologique",
      it: "biologic-profile",
      de: "biologic-profile",
    },
    translatedValues: {
      ENVIRONNEMENT: {
        en: "environment",
        fr: "environnement",
        it: "environment",
        de: "environment",
      },
      CONVENTIONNEL: {
        en: "conventional",
        fr: "conventionnel",
        it: "tradizionale",
        de: "konventionell",
      },
      ECOLOGIQUE: {
        en: "environment-friendly",
        fr: "ecologique",
        it: "rispettoso-dell-ambiente",
        de: "umweltfreundlich",
      },
      RAISONNEE: { en: "sustainable", fr: "raisonnee", it: "sostenibile", de: "integriert" },
      BIOLOGIQUE: { en: "organic", fr: "biologique", it: "biologico", de: "biologisch" },
      BIODYNAMIQUE: { en: "biodynamic", fr: "biodynamique", it: "biodinamico", de: "biodynamisch" },
      NATURE: { en: "natural", fr: "nature", it: "naturale", de: "natur" },
      BIOLOGIQUE_ET_NATURE: {
        en: "organics-and-natural",
        fr: "biologique-et-nature",
        it: "biologico-e-naturale",
        de: "biologisch-und-natur",
      },
      BIODYNAMIQUE_ET_NATURE: {
        en: "biodynamics-and-natural",
        fr: "biodynamique-et-nature",
        it: "biodinamico-e-naturale",
        de: "biodynamisch-und-natur",
      },
      TRIPLE_A: { en: "triple-a", fr: "triple-a", it: "triple-a", de: "triple-a" },
      TRIPLE_A_ET_BIOLOGIQUE: {
        en: "triple-a-and-organic",
        fr: "triple-a-et-biologique",
        it: "triple-a-e-biologico",
        de: "triple-a-und-biologisch",
      },
      TRIPLE_A_ET_BIODYNAMIQUE: {
        en: "triple-a-and-biodynamic",
        fr: "triple-a-et-biodynamique",
        it: "triple-a-e-biodinamico",
        de: "triple-a-und-biodynamisch",
      },
    },
    type: "enum",
    priority: 21,
  },
  grapeVariety: {
    translatedKey: {
      en: "grape-variety",
      fr: "cepage",
      it: "vitigno",
      de: "rebsorte",
    },
    translatedValues: {
      AGLIANICO: { en: "aglianico", fr: "aglianico", it: "aglianico", de: "aglianico" },
      ALIGOTE: { en: "aligote", fr: "aligote", it: "aligote", de: "aligote" },
      ALTESSE: { en: "altesse", fr: "altesse", it: "altesse", de: "altesse" },
      ARBANE: { en: "arbane", fr: "arbane", it: "arbane", de: "arbane" },
      BACO: { en: "baco", fr: "baco", it: "baco", de: "baco" },
      BARBAROSSA: { en: "barbarossa", fr: "barbarossa", it: "barbarossa", de: "barbarossa" },
      BARBERA: { en: "barbera", fr: "barbera", it: "barbera", de: "barbera" },
      BOURBOULENC: { en: "bourboulenc", fr: "bourboulenc", it: "bourboulenc", de: "bourboulenc" },
      CABERNET_FRANC: {
        en: "cabernet-franc",
        fr: "cabernet-franc",
        it: "cabernet-franc",
        de: "cabernet-franc",
      },
      CABERNET_SAUVIGNON: {
        en: "cabernet-sauvignon",
        fr: "cabernet-sauvignon",
        it: "cabernet-sauvignon",
        de: "cabernet-sauvignon",
      },
      CAMARALET: { en: "camaralet", fr: "camaralet", it: "camaralet", de: "camaralet" },
      CARIGNAN: { en: "carignan", fr: "carignan", it: "carignan", de: "carignan" },
      CARMENERE: { en: "carmenere", fr: "carmenere", it: "carmenere", de: "carmenere" },
      CARTOIXA: { en: "cartoixa", fr: "cartoixa", it: "cartoixa", de: "cartoixa" },
      CHARDONNAY: { en: "chardonnay", fr: "chardonnay", it: "chardonnay", de: "chardonnay" },
      CHENIN_BLANC: {
        en: "chenin-blanc",
        fr: "chenin-blanc",
        it: "chenin-blanc",
        de: "chenin-blanc",
      },
      CINSAULT: { en: "cinsault", fr: "cinsault", it: "cinsault", de: "cinsault" },
      CLAIRETTE: { en: "clairette", fr: "clairette", it: "clairette", de: "clairette" },
      COLOMBARD: { en: "colombard", fr: "colombard", it: "colombard", de: "colombard" },
      CORVINA: { en: "corvina", fr: "corvina", it: "corvina", de: "corvina" },
      COUNOISE: { en: "counoise", fr: "counoise", it: "counoise", de: "counoise" },
      DOLCETTO: { en: "dolcetto", fr: "dolcetto", it: "dolcetto", de: "dolcetto" },
      DOUCE_NOIRE: { en: "douce-noire", fr: "douce-noire", it: "douce-noire", de: "douce-noire" },
      FOLLE_BLANCHE: {
        en: "la-folle-blanche",
        fr: "la-folle-blanche",
        it: "la-folle-blanche",
        de: "la-folle-blanche",
      },
      FURMINT: { en: "furmint", fr: "furmint", it: "furmint", de: "furmint" },
      GAMAY: { en: "gamay", fr: "gamay", it: "gamay", de: "gamay" },
      GEWURZTRAMINER: {
        en: "gewurztraminer",
        fr: "gewurztraminer",
        it: "gewurztraminer",
        de: "gewurztraminer",
      },
      GIBERT: { en: "gibert", fr: "gibert", it: "gibert", de: "gibert" },
      GRENACHE: { en: "grenache", fr: "grenache", it: "grenache", de: "grenache" },
      GRENACHE_BLANC: {
        en: "grenache-blanc",
        fr: "grenache-blanc",
        it: "grenache-blanc",
        de: "grenache-blanc",
      },
      GRENACHE_GRIS: {
        en: "grenache-gris",
        fr: "grenache-gris",
        it: "grenache-gris",
        de: "grenache-gris",
      },
      GROS_MANSENG: {
        en: "gros-manseng",
        fr: "gros-manseng",
        it: "gros-manseng",
        de: "gros-manseng",
      },
      JACQUERE: { en: "jacquere", fr: "jacquere", it: "jacquere", de: "jacquere" },
      JURANCON_NOIR: {
        en: "jurancon-noir",
        fr: "jurancon-noir",
        it: "jurancon-noir",
        de: "jurancon-noir",
      },
      LAUZET: { en: "lauzet", fr: "lauzet", it: "lauzet", de: "lauzet" },
      MACABEU: { en: "macabeu", fr: "macabeu", it: "macabeu", de: "macabeu" },
      MALBEC: { en: "malbec", fr: "malbec", it: "malbec", de: "malbec" },
      MALVOISIE: { en: "malvoisie", fr: "malvoisie", it: "malvoisie", de: "malvoisie" },
      MARSANNE: { en: "marsanne", fr: "marsanne", it: "marsanne", de: "marsanne" },
      MELON_DE_BOURGOGNE: {
        en: "melon-de_bourgogne",
        fr: "melon-de_bourgogne",
        it: "melon-de_bourgogne",
        de: "melon-de_bourgogne",
      },
      MERLOT: { en: "merlot", fr: "merlot", it: "merlot", de: "merlot" },
      MONDEUSE: { en: "mondeuse", fr: "mondeuse", it: "mondeuse", de: "mondeuse" },
      MONDEUSE_BLANCHE: {
        en: "mondeuse-blanche",
        fr: "mondeuse-blanche",
        it: "mondeuse-blanche",
        de: "mondeuse-blanche",
      },
      MONTEPULCIANO: {
        en: "montepulciano",
        fr: "montepulciano",
        it: "montepulciano",
        de: "montepulciano",
      },
      MOURVEDRE: { en: "mourvedre", fr: "mourvedre", it: "mourvedre", de: "mourvedre" },
      MUSCADELLE: { en: "muscadelle", fr: "muscadelle", it: "muscadelle", de: "muscadelle" },
      MUSCARDIN: { en: "muscardin", fr: "muscardin", it: "muscardin", de: "muscardin" },
      MUSCAT: { en: "muscat", fr: "muscat", it: "muscat", de: "muscat" },
      MUSCAT_BLANC_A_PETITS_GRAINS: {
        en: "muscat-blanc_a_petits_grains",
        fr: "muscat-blanc_a_petits_grains",
        it: "muscat-blanc_a_petits_grains",
        de: "muscat-blanc_a_petits_grains",
      },
      NEBBIOLO: { en: "nebbiolo", fr: "nebbiolo", it: "nebbiolo", de: "nebbiolo" },
      NEGRETTE: { en: "negrette", fr: "negrette", it: "negrette", de: "negrette" },
      NERELLO_CAPUCCIO: {
        en: "nerello-capuccio",
        fr: "nerello-capuccio",
        it: "nerello-capuccio",
        de: "nerello-capuccio",
      },
      NERELLO_MASCALESE: {
        en: "nerello-mascalese",
        fr: "nerello-mascalese",
        it: "nerello-mascalese",
        de: "nerello-mascalese",
      },
      NERO_D_AVOLA: {
        en: "nero-d_avola",
        fr: "nero-d_avola",
        it: "nero-d_avola",
        de: "nero-d_avola",
      },
      NIELLUCCIU: { en: "niellucciu", fr: "niellucciu", it: "niellucciu", de: "niellucciu" },
      NOUAL: { en: "noual", fr: "noual", it: "noual", de: "noual" },
      PELAVERGA_PICCOLO: {
        en: "pelaverga-piccolo",
        fr: "pelaverga-piccolo",
        it: "pelaverga-piccolo",
        de: "pelaverga-piccolo",
      },
      PERDO_XIMENEZ: {
        en: "perdo-ximenez",
        fr: "perdo-ximenez",
        it: "perdo-ximenez",
        de: "perdo-ximenez",
      },
      PERSAN: { en: "persan", fr: "persan", it: "persan", de: "persan" },
      PETITE_ARVINE: {
        en: "petite-arvine",
        fr: "petite-arvine",
        it: "petite-arvine",
        de: "petite-arvine",
      },
      PETIT_MANSENG: {
        en: "petit-manseng",
        fr: "petit-manseng",
        it: "petit-manseng",
        de: "petit-manseng",
      },
      PETIT_MESLIER: {
        en: "petit-meslier",
        fr: "petit-meslier",
        it: "petit-meslier",
        de: "petit-meslier",
      },
      PETIT_VERDOT: {
        en: "petit-verdot",
        fr: "petit-verdot",
        it: "petit-verdot",
        de: "petit-verdot",
      },
      PINOT_BLANC: { en: "pinot-blanc", fr: "pinot-blanc", it: "pinot-blanc", de: "pinot-blanc" },
      PINOT_GRIS: { en: "pinot-gris", fr: "pinot-gris", it: "pinot-gris", de: "pinot-gris" },
      PINOT_MEUNIER: {
        en: "pinot-meunier",
        fr: "pinot-meunier",
        it: "pinot-meunier",
        de: "pinot-meunier",
      },
      PINOT_NOIR: { en: "pinot-noir", fr: "pinot-noir", it: "pinot-noir", de: "pinot-noir" },
      POULSARD: { en: "poulsard", fr: "poulsard", it: "poulsard", de: "poulsard" },
      RIBOLLA_GIALLA: {
        en: "ribolla-gialla",
        fr: "ribolla-gialla",
        it: "ribolla-gialla",
        de: "ribolla-gialla",
      },
      RIESLING: { en: "riesling", fr: "riesling", it: "riesling", de: "riesling" },
      RONDINELLA: {
        en: "la-rondinella",
        fr: "la-rondinella",
        it: "la-rondinella",
        de: "la-rondinella",
      },
      ROUSSANNE: { en: "roussanne", fr: "roussanne", it: "roussanne", de: "roussanne" },
      SANGIOVESE: { en: "sangiovese", fr: "sangiovese", it: "sangiovese", de: "sangiovese" },
      SAUVIGNON_A_GROS_GRAINS: {
        en: "sauvignon-a_gros_grains",
        fr: "sauvignon-a_gros_grains",
        it: "sauvignon-a_gros_grains",
        de: "sauvignon-a_gros_grains",
      },
      SAUVIGNON_BLANC: {
        en: "sauvignon-blanc",
        fr: "sauvignon-blanc",
        it: "sauvignon-blanc",
        de: "sauvignon-blanc",
      },
      SAVAGNIN: { en: "savagnin", fr: "savagnin", it: "savagnin", de: "savagnin" },
      SCIACCARELLU: {
        en: "sciaccarellu",
        fr: "sciaccarellu",
        it: "sciaccarellu",
        de: "sciaccarellu",
      },
      SEMILLON: { en: "semillon", fr: "semillon", it: "semillon", de: "semillon" },
      SYLVANER: { en: "sylvaner", fr: "sylvaner", it: "sylvaner", de: "sylvaner" },
      SYRAH: { en: "syrah", fr: "syrah", it: "syrah", de: "syrah" },
      TANNAT: { en: "tannat", fr: "tannat", it: "tannat", de: "tannat" },
      TEMPRANILLO: { en: "tempranillo", fr: "tempranillo", it: "tempranillo", de: "tempranillo" },
      TERRET_NOIR: { en: "terret-noir", fr: "terret-noir", it: "terret-noir", de: "terret-noir" },
      TREBBIANO: { en: "trebbiano", fr: "trebbiano", it: "trebbiano", de: "trebbiano" },
      TROUSSEAU: { en: "trousseau", fr: "trousseau", it: "trousseau", de: "trousseau" },
      UGNI: { en: "ugni", fr: "ugni", it: "ugni", de: "ugni" },
      UGNI_BLANC: { en: "ugni-blanc", fr: "ugni-blanc", it: "ugni-blanc", de: "ugni-blanc" },
      VACCARESE: { en: "vaccarese", fr: "vaccarese", it: "vaccarese", de: "vaccarese" },
      VALDIGUIE: { en: "valdiguie", fr: "valdiguie", it: "valdiguie", de: "valdiguie" },
      VERMENTINO: { en: "vermentino", fr: "vermentino", it: "vermentino", de: "vermentino" },
      VIOGNIER: { en: "viognier", fr: "viognier", it: "viognier", de: "viognier" },
      ZINFANDEL: { en: "zinfandel", fr: "zinfandel", it: "zinfandel", de: "zinfandel" },
    },
    type: "enum",
    priority: 24,
  },
  peak: {
    translatedKey: {
      en: "peak",
      fr: "apogee",
      it: "peak",
      de: "peak",
    },
    translatedValues: {
      A_BOIRE: { en: "to-drink", fr: "a-boire", it: "to-drink", de: "to-drink" },
      COLLECTION: { en: "collectable", fr: "collection", it: "collectable", de: "collectable" },
      VIEILLISSEMENT: {
        en: "laying-down",
        fr: "vieillissement",
        it: "laying-down",
        de: "laying-down",
      },
    },
    type: "enum",
    priority: 25,
  },
  alcoholLevel: {
    translatedKey: {
      en: "percentage-alcohol",
      fr: "pourcentage-alcool",
      it: "gradazione-alcolica",
      de: "prozent-alkohol",
    },
    type: "identical",
    priority: 26,
  },
  productCategory: {
    translatedKey: {
      en: "product-category",
      fr: "categorie-produit",
      it: "categoria-prodotto",
      de: "produkt-kategorie",
    },
    translatedValues: {
      PRODUITS_INTERMEDIAIRES: {
        en: "produits-intermediaires",
        fr: "produits-intermediaires",
        it: "produits-intermediaires",
        de: "produits-intermediaires",
      },
      VDN: { en: "fortified-wine", fr: "vdn", it: "fortified-wine", de: "fortified-wine" },
      VINS_AOC_AVEC_IG_AOP: {
        en: "vins-aoc-avec-ig-aop",
        fr: "vins-aoc-avec-ig-aop",
        it: "vins-aoc-avec-ig-aop",
        de: "vins-aoc-avec-ig-aop",
      },
      VINS_MOUSSEUX: {
        en: "vins-mousseux",
        fr: "vins-mousseux",
        it: "vins-mousseux",
        de: "vins-mousseux",
      },
      SPIRITUEUX: { en: "spirits", fr: "spiritueux", it: "distillati", de: "spirituosen" },
      AUTRES_VINS: { en: "autres-vins", fr: "autres-vins", it: "autres-vins", de: "autres-vins" },
      BIERE: { en: "beer", fr: "biere", it: "beer", de: "beer" },
    },
    type: "enum",
    priority: 27,
  },
  availableQuantity: {
    translatedKey: {
      en: "available-quantity",
      fr: "en-stock",
      it: "quantita-disponibile",
      de: "verfugbare-menge",
    },
    type: "identical",
    priority: 28,
  },
  hasLotDiscount: {
    translatedKey: {
      en: "reduced-prices",
      fr: "prix-reduits",
      it: "prezzi-scontati",
      de: "reduzierte-preise",
    },
    type: "boolean",
    priority: 29,
  },
  hasDiscount: {
    translatedKey: {
      en: "declining-prices",
      fr: "prix-en-baisse",
      it: "promozioni",
      de: "sinkende-preise",
    },
    type: "boolean",
    priority: 30,
  },
  domainName: {
    translatedKey: {
      en: "domain",
      fr: "domaine",
      it: "tenuta",
      de: "weingut",
    },
    type: "transform",
    priority: 31,
  },
  query: {
    translatedKey: {
      en: "search",
      fr: "recherche",
      it: "ricerca",
      de: "suchen",
    },
    type: "query",
    priority: 32,
  },
  page: {
    translatedKey: {
      en: "page",
      fr: "page",
      it: "pagina",
      de: "seite",
    },
    type: "identical",
    priority: 33,
  },
  auctionCatalogId: {
    translatedKey: {
      en: "ref",
      fr: "ref",
      it: "ref",
      de: "ref",
    },
    type: "identical",
    priority: 34,
  },
  quintessenceSale: {
    translatedKey: {
      en: "quintessence",
      fr: "quintessence",
      it: "quintessence",
      de: "quintessence",
    },
    type: "identical",
    priority: 35,
  },
  auctionCatalogStartDate: {
    translatedKey: {
      en: "new-arrival",
      fr: "nouveautes",
      it: "new-entry",
      de: "neuheiten",
    },
    type: "boolean",
    priority: 36,
  },
  sortBy: {
    translatedKey: {
      en: "order-by",
      fr: "order-by",
      it: "order-by",
      de: "order-by",
    },
    translatedValues: {
      [`${PLPIndexName}_price_asc`]: {
        en: "price-asc",
        fr: "price-asc",
        it: "price-asc",
        de: "price-asc",
      },
      [`${PLPIndexName}_price_desc`]: {
        en: "price-desc",
        fr: "price-desc",
        it: "price-desc",
        de: "price-desc",
      },
      [`${PLPIndexName}_bid_count_asc`]: {
        en: "bid-count-asc",
        fr: "bid-count-asc",
        it: "bid-count-asc",
        de: "bid-count-asc",
      },
      [`${PLPIndexName}_bid_count_desc`]: {
        en: "bid-count-desc",
        fr: "bid-count-desc",
        it: "bid-count-desc",
        de: "bid-count-desc",
      },
      [`${PLPIndexName}_bid_end_date_asc`]: {
        en: "end-date-asc",
        fr: "end-date-asc",
        it: "end-date-asc",
        de: "end-date-asc",
      },
      [`${PLPIndexName}_bid_end_date_desc`]: {
        en: "end-date-desc",
        fr: "end-date-desc",
        it: "end-date-desc",
        de: "end-date-desc",
      },
      [`${PLPIndexName}_bid_watch_asc`]: {
        en: "watch-number-asc",
        fr: "watch-number-asc",
        it: "watch-number-asc",
        de: "watch-number-asc",
      },
      [`${PLPIndexName}_bid_watch_desc`]: {
        en: "watch-number-desc",
        fr: "watch-number-desc",
        it: "watch-number-desc",
        de: "watch-number-desc",
      },
      [`${PLPIndexName}_vintage_asc`]: {
        en: "vintage-asc",
        fr: "vintage-asc",
        it: "vintage-asc",
        de: "vintage-asc",
      },
      [`${PLPIndexName}_vintage_desc`]: {
        en: "vintage-desc",
        fr: "vintage-desc",
        it: "vintage-desc",
        de: "vintage-desc",
      },
    },
    type: "enum",
    priority: 1000,
  },
};

/**
 * This function reverses the valueCodeToTranslated object
 * It gives an object having the translated value as key and the code as value.
 */
const generateValueTranslatedToCode = () => {
  const valueTranslatedToCode = {} as ValueTranslatedToCode;
  for (const filter in codeToTranslated) {
    const typedFilter = filter as RefinementType;
    const currentFilter = codeToTranslated[typedFilter];
    if (currentFilter.type === "enum") {
      valueTranslatedToCode[typedFilter] = {};
      const filterValues = currentFilter["translatedValues"];
      for (const value in filterValues) {
        for (const language in filterValues[value]) {
          const typedLanguage = language as Locale;
          valueTranslatedToCode[typedFilter][filterValues[value][typedLanguage]] = value;
        }
      }
    }
  }

  return valueTranslatedToCode;
};

export const valueTranslatedToCode = generateValueTranslatedToCode();

/**
 * This function reverses the keyCodeToTranslated object
 * It gives an object having the translated key as key and, for value, the algolia key name and its type..
 */
const generateKeyTranslatedToCode = () => {
  const keyTranslatedToCode = {} as KeyTranslatedToCode;
  for (const filter in codeToTranslated) {
    const typedFilter = filter as RefinementType;
    for (const language in codeToTranslated[typedFilter]["translatedKey"]) {
      const typedLanguage = language as Locale;
      keyTranslatedToCode[codeToTranslated[typedFilter]["translatedKey"][typedLanguage]] = {
        name: typedFilter,
        type: codeToTranslated[typedFilter]["type"],
      };
    }
  }

  return keyTranslatedToCode;
};

export const keyTranslatedToCode = generateKeyTranslatedToCode();

/**
 * This function generates a list of all the algolia keys, with their type and priority.
 */
const generateKeyList = () => {
  const tempKeyList: TempKeyList = [];
  let keyList: KeyList = [];
  for (const key in codeToTranslated) {
    if (key === "sortBy") continue;
    const typedKey = key as RefinementType;
    tempKeyList.push({
      name: typedKey,
      type: codeToTranslated[typedKey]["type"],
      priority: codeToTranslated[typedKey]["priority"],
    });
  }
  keyList = tempKeyList
    .sort((a, b) => a.priority - b.priority)
    .map(element => {
      return {
        name: element.name,
        type: element.type,
      };
    });

  return keyList;
};

export const keyList = generateKeyList();

/**
 * This function generates a list of all the translations of the sortBy algolia key.
 */
const generateSortByTranslationsList = (): string[] => {
  const sortByTranslationsList: string[] = [];
  const sortByConfig = codeToTranslated["sortBy"];
  if (sortByConfig.type === "enum") {
    for (const value in sortByConfig["translatedValues"]) {
      for (const language in sortByConfig["translatedValues"][value]) {
        const typedLanguage = language as Locale;
        sortByTranslationsList.push(sortByConfig["translatedValues"][value][typedLanguage]);
      }
    }
  }

  return sortByTranslationsList;
};

export const sortByTranslationsList = generateSortByTranslationsList();
