import { PLPIndexName } from "@/hooks/useAlgoliaRefinements";
import { translatedLinksKeys } from "@/urls/linksTranslation";

import { BIO_VALUES, NATURE_VALUES } from "./constants";

export type MenuItem =
  | { label: keyof typeof dynamicMenuLinks; type: "link"; items?: never }
  | {
      label: string;
      type: "navigator" | "section";
      items: MenuItem[];
    };

export type MarketingTagMenuItem = {
  label: string;
  params: object;
};

export const dynamicMenuData: MenuItem[] = [
  {
    label: "allOurWines",
    type: "navigator",
    items: [
      {
        label: "allOurWinesOnSale",
        type: "section",
        items: [
          { label: "auctions", type: "link" },
          { label: "eCaviste", type: "link" },
          { label: "primeurs", type: "link" },
        ],
      },
      {
        label: "ourSpecialties",
        type: "section",
        items: [
          { label: "mustHaves", type: "link" },
          { label: "bioWines", type: "link" },
          { label: "naturalWines", type: "link" },
          { label: "tripleAWines", type: "link" },
          { label: "plusTenYearsVintages", type: "link" },
          { label: "risingStars", type: "link" },
        ],
      },
      {
        label: "lotsAndFormats",
        type: "section",
        items: [
          { label: "largeFormats", type: "link" },
          { label: "woodenCasesAndBoxes", type: "link" },
        ],
      },
      {
        label: "spirits",
        type: "section",
        items: [
          { label: "whisky", type: "link" },
          { label: "cognac", type: "link" },
          { label: "armagnac", type: "link" },
          { label: "rum", type: "link" },
        ],
      },
      {
        label: "greatDeals",
        type: "section",
        items: [
          { label: "lastChance", type: "link" },
          { label: "reducedPricesByQuantities", type: "link" },
        ],
      },
    ],
  },
  {
    label: "winesByRegion",
    type: "navigator",
    items: [
      {
        label: "winesByRegion",
        type: "section",
        items: [
          { label: "bordeaux", type: "link" },
          { label: "bourgogne", type: "link" },
          { label: "rhone", type: "link" },
          { label: "champagne", type: "link" },
          { label: "loire", type: "link" },
          { label: "languedoc", type: "link" },
          { label: "roussillon", type: "link" },
          { label: "alsace", type: "link" },
          { label: "jura", type: "link" },
          { label: "beaujolais", type: "link" },
          { label: "provence", type: "link" },
          { label: "corsica", type: "link" },
          { label: "savoie", type: "link" },
          { label: "southWest", type: "link" },
          { label: "frenchWines", type: "link" },
        ],
      },
      {
        label: "winesByCountry",
        type: "section",
        items: [
          { label: "italie", type: "link" },
          { label: "spain", type: "link" },
          { label: "portugal", type: "link" },
          { label: "germany", type: "link" },
          { label: "unitedStates", type: "link" },
          { label: "argentine", type: "link" },
          { label: "chili", type: "link" },
          { label: "southAfrica", type: "link" },
          { label: "australia", type: "link" },
          { label: "newZeland", type: "link" },
          { label: "otherCountries", type: "link" },
        ],
      },
      {
        label: "bordeauxByAppellation",
        type: "section",
        items: [
          { label: "saintEmilion", type: "link" },
          { label: "medoc", type: "link" },
          { label: "graves", type: "link" },
          { label: "margaux", type: "link" },
          { label: "pauillac", type: "link" },
        ],
      },
      {
        label: "bourgogneByAppellation",
        type: "section",
        items: [
          { label: "vosneRomanee", type: "link" },
          { label: "corton", type: "link" },
          { label: "volnay", type: "link" },
          { label: "montrachet", type: "link" },
          { label: "chablis", type: "link" },
        ],
      },
      {
        label: "rhoneByAppellation",
        type: "section",
        items: [
          { label: "coteRotie", type: "link" },
          { label: "hermitage", type: "link" },
          { label: "chateauneufDuPape", type: "link" },
        ],
      },
    ],
  },
  {
    label: "auctions",
    type: "navigator",
    items: [
      {
        label: "promotions",
        type: "section",
        items: [
          { label: "lotsWithoutBids", type: "link" },
          { label: "lotsWithoutReservePrice", type: "link" },
          { label: "newLots", type: "link" },
        ],
      },
      {
        label: "AllOurAuctions",
        type: "section",
        items: [{ label: "auctionCatalogs", type: "link" }],
      },
    ],
  },
  {
    label: "servicesPlus",
    type: "navigator",
    items: [
      {
        label: "ourTailorMadeServices",
        type: "section",
        items: [
          { label: "loyaltyProgram", type: "link" },
          { label: "tailorMadeCellar", type: "link" },
          { label: "storageCellar", type: "link" },
          { label: "corporateGifts", type: "link" },
          { label: "celebrationsAndWeddings", type: "link" },
        ],
      },
    ],
  },
  { label: "helpMeChoose", type: "link" },
  // @ts-expect-error weeklyShowcase is a special link using Prismic that will be catched by the DesktopDynamicMenu component, therefore it is not needed to have its configuration.
  { label: "weeklyShowcase", type: "link" },
  { label: "mustHaves", type: "link" },
];

const largeFormats = [
  "DOUBLE_MAGNUM",
  "IMPERIALE",
  "NABUCHODONOSOR",
  "JEROBOAM",
  "MAGNUM",
  "MATHUSALEM",
  "REHOBOAM",
  "SALMANAZAR",
];

export type DynamicMenuLinkType = {
  pageKey: translatedLinksKeys;
  params: object;
};

// Hardcoded: values are from what it is in idw prod today
const otherCountries = [
  "ANTIGUA_ET_BARBUDA",
  "ANTILLES",
  "AUTRES_PAYS",
  "AUTRICHE",
  "BAHAMAS",
  "BARBADE",
  "BELGIQUE",
  "BELIZE",
  "BERMUDES",
  "BOSNIE_HERZEGOVINE",
  "BRESIL",
  "CANADA",
  "CAP_VERT",
  "CARAIBES",
  "CHINE",
  "COLOMBIE",
  "CROATIE",
  "CUBA",
  "DANEMARK",
  "ECOSSE",
  "FIDJI",
  "GRECE",
  "GRENADE",
  "GUADELOUPE",
  "GUATEMALA",
  "GUYANA",
  "GUYANE",
  "HAITI",
  "HONGRIE",
  "ILE_MAURICE",
  "INDE",
  "IRLANDE",
  "ISRAEL",
  "JAMAIQUE",
  "JAPON",
  "KENYA",
  "LA_REUNION",
  "LIBAN",
  "MACEDOINE",
  "MADAGASCAR",
  "MAROC",
  "MARTINIQUE",
  "MEXIQUE",
  "NEPAL",
  "NICARAGUA",
  "PANAMA",
  "PEROU",
  "PHILIPPINES",
  "POLOGNE",
  "POLYNESIE_FRANCAISE",
  "PORTO_RICO",
  "REPUBLIQUE_DOMINICAINE",
  "REPUBLIQUE_TCHEQUE",
  "ROYAUME_UNI",
  "RUSSIE",
  "SAINT_MARTIN",
  "SAINTE_LUCIE",
  "SEYCHELLES",
  "SLOVAQUIE",
  "SLOVENIE",
  "SRI_LANKA",
  "SUEDE",
  "SUISSE",
  "TAIWAN",
  "TCHECOSLOVAQUIE",
  "TRINITE_ET_TOBAGO",
  "URUGUAY",
  "VENEZUELA",
];

export const noSpirits = [
  "AUTRES_VINS",
  "BIERE",
  "PRODUITS_INTERMEDIAIRES",
  "VDN",
  "VINS_AOC_AVEC_IG_AOP",
  "VINS_MOUSSEUX",
];

export const plusTenYearsVintages = [
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980",
  "1979",
  "1978",
  "1977",
  "1976",
  "1975",
  "1974",
  "1973",
  "1972",
  "1971",
  "1970",
  "1969",
  "1968",
  "1967",
  "1966",
  "1965",
  "1964",
  "1963",
  "1962",
  "1961",
  "1960",
  "1959",
  "1958",
  "1957",
  "1956",
  "1955",
  "1954",
  "1953",
  "1952",
  "1951",
  "1950",
  "1949",
  "1948",
  "1947",
  "1946",
  "1945",
  "1944",
  "1943",
  "1942",
  "1941",
  "1940",
  "1939",
  "1938",
  "1937",
  "1936",
  "1935",
  "1934",
  "1933",
  "1932",
  "1931",
  "1930",
  "1929",
  "1928",
  "1927",
  "1926",
  "1925",
  "1924",
  "1923",
  "1922",
  "1921",
  "1920",
  "1919",
  "1918",
  "1917",
  "1916",
  "1915",
  "1914",
  "1913",
  "1912",
  "1911",
  "1910",
  "1909",
  "1908",
  "1907",
  "1906",
  "1905",
  "1904",
  "1903",
  "1902",
  "1901",
  "1900",
  "1899",
  "1898",
  "1897",
  "1896",
  "1895",
  "1894",
  "1893",
  "1892",
  "1891",
  "1890",
  "1889",
  "1888",
  "1887",
  "1886",
  "1885",
  "1884",
  "1883",
  "1882",
  "1881",
  "1880",
  "1879",
  "1878",
  "1877",
  "1876",
  "1875",
  "1874",
  "1873",
  "1872",
  "1871",
  "1870",
  "1869",
  "1868",
  "1867",
  "1866",
  "1865",
  "1864",
  "1863",
  "1862",
  "1861",
  "1860",
  "1859",
  "1858",
  "1857",
  "1856",
  "1855",
  "1854",
  "1853",
  "1852",
  "1851",
  "1850",
  "1849",
  "1848",
  "1847",
  "1846",
  "1845",
  "1844",
  "1843",
  "1842",
  "1841",
  "1840",
  "1839",
  "1838",
  "1837",
  "1836",
  "1835",
  "1834",
  "1833",
  "1832",
  "1831",
  "1830",
  "1829",
  "1828",
  "1827",
  "1826",
  "1825",
  "1824",
  "1823",
  "1822",
  "1821",
  "1820",
  "1819",
  "1818",
  "1817",
  "1816",
  "1815",
  "1814",
  "1813",
  "1812",
  "1811",
  "1810",
  "1809",
  "1808",
  "1807",
  "1806",
  "1805",
  "1804",
  "1803",
  "1802",
  "1801",
  "1800",
  "1799",
  "1798",
  "1797",
];

export const SagaMillesime = [
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  ...plusTenYearsVintages,
];

export const dynamicMenuLinks = {
  // All our wines
  allOurWinesOnSale: { pageKey: "BUY_WINE_URL", params: {} },
  auctions: {
    pageKey: "BUY_WINE_URL",
    params: { isDirectPurchase: ["false"], sortBy: [`${PLPIndexName}_price_desc`] },
  },
  eCaviste: { pageKey: "BUY_WINE_URL", params: { isDirectPurchase: ["true"] } },
  primeurs: { pageKey: "PRIMEURS_URL", params: {} },
  mustHaves: {
    pageKey: "BUY_WINE_URL",
    params: { tags: ["LES-INDISPENSABLES"], sortBy: [`${PLPIndexName}_price_asc`] },
  },
  bioWines: { pageKey: "BUY_WINE_URL", params: { biologicProfile: BIO_VALUES } },
  naturalWines: { pageKey: "BUY_WINE_URL", params: { biologicProfile: NATURE_VALUES } },
  tripleAWines: { pageKey: "TRIPLE_A_WINES", params: {} },
  // TODO 1: how to solve this?
  plusTenYearsVintages: { pageKey: "BUY_WINE_URL", params: { vintage: plusTenYearsVintages } },
  risingStars: { pageKey: "BUY_WINE_URL", params: { status: ["ETOILE_MONTANTE"] } },
  largeFormats: { pageKey: "BUY_WINE_URL", params: { bottleSize: largeFormats } },
  woodenCasesAndBoxes: { pageKey: "BUY_WINE_URL", params: { woodenCase: ["true"] } },
  lastChance: {
    pageKey: "BUY_WINE_URL",
    params: { tags: ["DERNIERE-CHANCE"], sortBy: [`${PLPIndexName}_price_asc`] },
  },
  reducedPricesByQuantities: { pageKey: "BUY_WINE_URL", params: { hasLotDiscount: ["true"] } },
  // Our wines by region
  bordeaux: { pageKey: "BUY_WINE_URL", params: { region: ["BORDEAUX"] } },
  bourgogne: { pageKey: "BUY_WINE_URL", params: { region: ["BOURGOGNE"] } },
  rhone: { pageKey: "BUY_WINE_URL", params: { region: ["VALLEE_DU_RHONE"] } },
  champagne: { pageKey: "BUY_WINE_URL", params: { region: ["CHAMPAGNE"] } },
  loire: { pageKey: "BUY_WINE_URL", params: { region: ["VALLEE_DE_LA_LOIRE"] } },
  languedoc: { pageKey: "BUY_WINE_URL", params: { region: ["LANGUEDOC"] } },
  roussillon: { pageKey: "BUY_WINE_URL", params: { region: ["ROUSSILLON"] } },
  alsace: { pageKey: "BUY_WINE_URL", params: { region: ["ALSACE"] } },
  jura: { pageKey: "BUY_WINE_URL", params: { region: ["JURA"] } },
  beaujolais: { pageKey: "BUY_WINE_URL", params: { region: ["BEAUJOLAIS"] } },
  provence: { pageKey: "BUY_WINE_URL", params: { region: ["PROVENCE"] } },
  corsica: { pageKey: "BUY_WINE_URL", params: { region: ["CORSE"] } },
  savoie: { pageKey: "BUY_WINE_URL", params: { region: ["SAVOIE"] } },
  southWest: { pageKey: "BUY_WINE_URL", params: { region: ["SUD_OUEST"] } },
  frenchWines: { pageKey: "BUY_WINE_URL", params: { subregion: ["Vin de France"] } },
  // by country
  italie: { pageKey: "BUY_WINE_URL", params: { country: ["ITALIE"] } },
  spain: { pageKey: "BUY_WINE_URL", params: { country: ["ESPAGNE"] } },
  portugal: { pageKey: "BUY_WINE_URL", params: { country: ["PORTUGAL"] } },
  germany: { pageKey: "BUY_WINE_URL", params: { country: ["ALLEMAGNE"] } },
  unitedStates: { pageKey: "BUY_WINE_URL", params: { country: ["ETATS_UNIS"] } },
  argentine: { pageKey: "BUY_WINE_URL", params: { country: ["ARGENTINE"] } },
  chili: { pageKey: "BUY_WINE_URL", params: { country: ["CHILI"] } },
  southAfrica: { pageKey: "BUY_WINE_URL", params: { country: ["AFRIQUE_DU_SUD"] } },
  australia: { pageKey: "BUY_WINE_URL", params: { country: ["AUSTRALIE"] } },
  newZeland: { pageKey: "BUY_WINE_URL", params: { country: ["NOUVELLE_ZELANDE"] } },
  otherCountries: {
    pageKey: "BUY_WINE_URL",
    params: { country: otherCountries, productCategory: noSpirits },
  },
  // by appellation
  // Bourdeaux
  bordeauxByAppellation: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["BORDEAUX"] },
  },
  saintEmilion: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["BORDEAUX"], subregion: ["Saint-Emilion"] },
  },
  medoc: { pageKey: "BUY_WINE_URL", params: { region: ["BORDEAUX"], subregion: ["Médoc"] } },
  graves: { pageKey: "BUY_WINE_URL", params: { region: ["BORDEAUX"], subregion: ["Graves"] } },
  margaux: { pageKey: "BUY_WINE_URL", params: { region: ["BORDEAUX"], subregion: ["Margaux"] } },
  pauillac: { pageKey: "BUY_WINE_URL", params: { region: ["BORDEAUX"], subregion: ["Pauillac"] } },
  // Bourgogne
  bourgogneByAppellation: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["BOURGOGNE"] },
  },
  vosneRomanee: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["BOURGOGNE"], subregion: ["Vosne-Romanée"] },
  },
  corton: { pageKey: "BUY_WINE_URL", params: { region: ["BOURGOGNE"], subregion: ["Corton"] } },
  volnay: { pageKey: "BUY_WINE_URL", params: { region: ["BOURGOGNE"], subregion: ["Volnay"] } },
  montrachet: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["BOURGOGNE"], subregion: ["Montrachet"] },
  },
  chablis: { pageKey: "BUY_WINE_URL", params: { region: ["BOURGOGNE"], subregion: ["Chablis"] } },
  // rhone
  rhoneByAppellation: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["VALLEE_DU_RHONE"] },
  },
  coteRotie: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["VALLEE_DU_RHONE"], subregion: ["Côte-Rôtie"] },
  },
  hermitage: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["VALLEE_DU_RHONE"], subregion: ["Hermitage"] },
  },
  chateauneufDuPape: {
    pageKey: "BUY_WINE_URL",
    params: { region: ["VALLEE_DU_RHONE"], query: ["chateauneuf-du-pape"] },
  },
  // Auctions
  lotsWithoutBids: {
    pageKey: "BUY_WINE_URL",
    params: { isDirectPurchase: ["false"], hasBids: ["false"] },
  },
  lotsWithoutReservePrice: {
    pageKey: "BUY_WINE_URL",
    params: { isDirectPurchase: ["false"], hasReservePrice: ["false"] },
  },
  newLots: {
    pageKey: "BUY_WINE_URL",
    params: { isDirectPurchase: ["false"], tags: ["Les nouveautés"] },
  },
  auctionCatalogs: { pageKey: "BUY_WINE_URL", params: {} },
  loyaltyProgram: { pageKey: "LOYALTY_PROGRAM_URL", params: {} },
  tailorMadeCellar: { pageKey: "TAILORMADE_CELLAR_URL", params: {} },
  storageCellar: { pageKey: "WINE_STORAGE_URL", params: {} },
  corporateGifts: { pageKey: "BUSINESS_GIFTS_URL", params: {} },
  celebrationsAndWeddings: { pageKey: "CELEBRATION_URL", params: {} },
  // others
  helpMeChoose: { pageKey: "IM_A_NEWBIE_URL", params: {} },
  spirits: { pageKey: "BUY_WINE_URL", params: { productCategory: ["SPIRITUEUX"] } },
  whisky: { pageKey: "BUY_WINE_URL", params: { query: ["whisky"] } },
  cognac: { pageKey: "BUY_WINE_URL", params: { query: ["cognac"] } },
  armagnac: { pageKey: "BUY_WINE_URL", params: { query: ["armagnac"] } },
  rum: { pageKey: "BUY_WINE_URL", params: { query: ["rhum"] } },
} as const;

export const isMustHaveLink = (label: string) => label === "mustHaves";
export const isBio = (label: string) => label === "bioWines";

const servicesPlus = [
  "loyaltyProgram",
  "tailorMadeCellar",
  "storageCellar",
  "corporateGifts",
  "celebrationsAndWeddings",
] as const;

export type ServicePlusLabel = typeof servicesPlus[number];

export const isServicePlus = (label: string): label is ServicePlusLabel =>
  servicesPlus.includes(label as ServicePlusLabel);
