/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetAuctionItemBidEventCollectionParams } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of AuctionItemBidEvent resources.
 */
export const getAuctionItemBidEventCollection = (
  params?: GetAuctionItemBidEventCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/auction-item-bid-events`, method: "get", params, signal },
    options,
  );
};

export const getGetAuctionItemBidEventCollectionQueryKey = (
  params?: GetAuctionItemBidEventCollectionParams,
) => {
  return [`/api/v2/auction-item-bid-events`, ...(params ? [params] : [])] as const;
};

export const getGetAuctionItemBidEventCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>,
  TError = unknown,
>(
  params?: GetAuctionItemBidEventCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuctionItemBidEventCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>> = ({
    signal,
  }) => getAuctionItemBidEventCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuctionItemBidEventCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>
>;
export type GetAuctionItemBidEventCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of AuctionItemBidEvent resources.
 */
export const useGetAuctionItemBidEventCollection = <
  TData = Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>,
  TError = unknown,
>(
  params?: GetAuctionItemBidEventCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAuctionItemBidEventCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuctionItemBidEventCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a AuctionItemBidEvent resource.
 */
export const getAuctionItemBidEventItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v2/auction-item-bid-events/${id}`, method: "get", signal },
    options,
  );
};

export const getGetAuctionItemBidEventItemQueryKey = (id: string) => {
  return [`/api/v2/auction-item-bid-events/${id}`] as const;
};

export const getGetAuctionItemBidEventItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuctionItemBidEventItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionItemBidEventItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuctionItemBidEventItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuctionItemBidEventItem>>> = ({
    signal,
  }) => getAuctionItemBidEventItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuctionItemBidEventItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuctionItemBidEventItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuctionItemBidEventItem>>
>;
export type GetAuctionItemBidEventItemQueryError = unknown;

/**
 * @summary Retrieves a AuctionItemBidEvent resource.
 */
export const useGetAuctionItemBidEventItem = <
  TData = Awaited<ReturnType<typeof getAuctionItemBidEventItem>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getAuctionItemBidEventItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuctionItemBidEventItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
