/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  ApiVirtualCellarsVirtualCellarItemsGetSubresource200,
  ApiVirtualCellarsVirtualCellarItemsGetSubresourceParams,
  GetVirtualCellarItemCollection200,
  GetVirtualCellarItemCollectionParams,
  VirtualCellarItemJsonldShopVirtualCellarItemRead,
  VirtualCellarItemJsonldShopVirtualCellarItemWrite,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? A
  : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves the collection of VirtualCellarItem resources.
 */
export const getVirtualCellarItemCollection = (
  params?: GetVirtualCellarItemCollectionParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetVirtualCellarItemCollection200>(
    { url: `/api/v2/shop/virtual-cellar-items`, method: "get", params, signal },
    options,
  );
};

export const getGetVirtualCellarItemCollectionQueryKey = (
  params?: GetVirtualCellarItemCollectionParams,
) => {
  return [`/api/v2/shop/virtual-cellar-items`, ...(params ? [params] : [])] as const;
};

export const getGetVirtualCellarItemCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getVirtualCellarItemCollection>>,
  TError = unknown,
>(
  params?: GetVirtualCellarItemCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getVirtualCellarItemCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVirtualCellarItemCollectionQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVirtualCellarItemCollection>>> = ({
    signal,
  }) => getVirtualCellarItemCollection(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVirtualCellarItemCollection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetVirtualCellarItemCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVirtualCellarItemCollection>>
>;
export type GetVirtualCellarItemCollectionQueryError = unknown;

/**
 * @summary Retrieves the collection of VirtualCellarItem resources.
 */
export const useGetVirtualCellarItemCollection = <
  TData = Awaited<ReturnType<typeof getVirtualCellarItemCollection>>,
  TError = unknown,
>(
  params?: GetVirtualCellarItemCollectionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getVirtualCellarItemCollection>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetVirtualCellarItemCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Creates a VirtualCellarItem resource.
 */
export const postVirtualCellarItemCollection = (
  virtualCellarItemJsonldShopVirtualCellarItemWrite: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<VirtualCellarItemJsonldShopVirtualCellarItemRead>(
    {
      url: `/api/v2/shop/virtual-cellar-items`,
      method: "post",
      headers: { "Content-Type": "application/ld+json" },
      data: virtualCellarItemJsonldShopVirtualCellarItemWrite,
    },
    options,
  );
};

export const getPostVirtualCellarItemCollectionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postVirtualCellarItemCollection>>,
    TError,
    { data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postVirtualCellarItemCollection>>,
  TError,
  { data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postVirtualCellarItemCollection>>,
    { data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> }
  > = props => {
    const { data } = props ?? {};

    return postVirtualCellarItemCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostVirtualCellarItemCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postVirtualCellarItemCollection>>
>;
export type PostVirtualCellarItemCollectionMutationBody =
  NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite>;
export type PostVirtualCellarItemCollectionMutationError = void;

/**
 * @summary Creates a VirtualCellarItem resource.
 */
export const usePostVirtualCellarItemCollection = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postVirtualCellarItemCollection>>,
    TError,
    { data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getPostVirtualCellarItemCollectionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Retrieves a VirtualCellarItem resource.
 */
export const getVirtualCellarItemItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<VirtualCellarItemJsonldShopVirtualCellarItemRead>(
    { url: `/api/v2/shop/virtual-cellar-items/${id}`, method: "get", signal },
    options,
  );
};

export const getGetVirtualCellarItemItemQueryKey = (id: string) => {
  return [`/api/v2/shop/virtual-cellar-items/${id}`] as const;
};

export const getGetVirtualCellarItemItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getVirtualCellarItemItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getVirtualCellarItemItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVirtualCellarItemItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVirtualCellarItemItem>>> = ({
    signal,
  }) => getVirtualCellarItemItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getVirtualCellarItemItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetVirtualCellarItemItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVirtualCellarItemItem>>
>;
export type GetVirtualCellarItemItemQueryError = void;

/**
 * @summary Retrieves a VirtualCellarItem resource.
 */
export const useGetVirtualCellarItemItem = <
  TData = Awaited<ReturnType<typeof getVirtualCellarItemItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getVirtualCellarItemItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetVirtualCellarItemItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Replaces the VirtualCellarItem resource.
 */
export const putVirtualCellarItemItem = (
  id: string,
  virtualCellarItemJsonldShopVirtualCellarItemWrite: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<VirtualCellarItemJsonldShopVirtualCellarItemRead>(
    {
      url: `/api/v2/shop/virtual-cellar-items/${id}`,
      method: "put",
      headers: { "Content-Type": "application/ld+json" },
      data: virtualCellarItemJsonldShopVirtualCellarItemWrite,
    },
    options,
  );
};

export const getPutVirtualCellarItemItemMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putVirtualCellarItemItem>>,
    TError,
    { id: string; data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putVirtualCellarItemItem>>,
  TError,
  { id: string; data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putVirtualCellarItemItem>>,
    { id: string; data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> }
  > = props => {
    const { id, data } = props ?? {};

    return putVirtualCellarItemItem(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutVirtualCellarItemItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof putVirtualCellarItemItem>>
>;
export type PutVirtualCellarItemItemMutationBody =
  NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite>;
export type PutVirtualCellarItemItemMutationError = void;

/**
 * @summary Replaces the VirtualCellarItem resource.
 */
export const usePutVirtualCellarItemItem = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putVirtualCellarItemItem>>,
    TError,
    { id: string; data: NonReadonly<VirtualCellarItemJsonldShopVirtualCellarItemWrite> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getPutVirtualCellarItemItemMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Removes the VirtualCellarItem resource.
 */
export const deleteVirtualCellarItemItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/v2/shop/virtual-cellar-items/${id}`, method: "delete" },
    options,
  );
};

export const getDeleteVirtualCellarItemItemMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVirtualCellarItemItem>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVirtualCellarItemItem>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVirtualCellarItemItem>>,
    { id: string }
  > = props => {
    const { id } = props ?? {};

    return deleteVirtualCellarItemItem(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVirtualCellarItemItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVirtualCellarItemItem>>
>;

export type DeleteVirtualCellarItemItemMutationError = unknown;

/**
 * @summary Removes the VirtualCellarItem resource.
 */
export const useDeleteVirtualCellarItemItem = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVirtualCellarItemItem>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getDeleteVirtualCellarItemItemMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Retrieves the collection of VirtualCellarItem resources.
 */
export const apiVirtualCellarsVirtualCellarItemsGetSubresource = (
  id: string,
  params?: ApiVirtualCellarsVirtualCellarItemsGetSubresourceParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApiVirtualCellarsVirtualCellarItemsGetSubresource200>(
    {
      url: `/api/v2/shop/virtual-cellars/${id}/virtual-cellar-items`,
      method: "get",
      params,
      signal,
    },
    options,
  );
};

export const getApiVirtualCellarsVirtualCellarItemsGetSubresourceQueryKey = (
  id: string,
  params?: ApiVirtualCellarsVirtualCellarItemsGetSubresourceParams,
) => {
  return [
    `/api/v2/shop/virtual-cellars/${id}/virtual-cellar-items`,
    ...(params ? [params] : []),
  ] as const;
};

export const getApiVirtualCellarsVirtualCellarItemsGetSubresourceQueryOptions = <
  TData = Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>,
  TError = void,
>(
  id: string,
  params?: ApiVirtualCellarsVirtualCellarItemsGetSubresourceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getApiVirtualCellarsVirtualCellarItemsGetSubresourceQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>
  > = ({ signal }) =>
    apiVirtualCellarsVirtualCellarItemsGetSubresource(id, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiVirtualCellarsVirtualCellarItemsGetSubresourceQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>
>;
export type ApiVirtualCellarsVirtualCellarItemsGetSubresourceQueryError = void;

/**
 * @summary Retrieves the collection of VirtualCellarItem resources.
 */
export const useApiVirtualCellarsVirtualCellarItemsGetSubresource = <
  TData = Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>,
  TError = void,
>(
  id: string,
  params?: ApiVirtualCellarsVirtualCellarItemsGetSubresourceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof apiVirtualCellarsVirtualCellarItemsGetSubresource>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getApiVirtualCellarsVirtualCellarItemsGetSubresourceQueryOptions(
    id,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
