/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductVariantTranslationJsonld } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductVariantTranslation resource.
 */
export const adminGetProductVariantTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductVariantTranslationJsonld>(
    { url: `/api/v2/admin/product-variant-translation/${id}`, method: "get", signal },
    options,
  );
};

export const getAdminGetProductVariantTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/admin/product-variant-translation/${id}`] as const;
};

export const getAdminGetProductVariantTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetProductVariantTranslationItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>
  > = ({ signal }) => adminGetProductVariantTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetProductVariantTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>
>;
export type AdminGetProductVariantTranslationItemQueryError = void;

/**
 * @summary Retrieves a ProductVariantTranslation resource.
 */
export const useAdminGetProductVariantTranslationItem = <
  TData = Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductVariantTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetProductVariantTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a ProductVariantTranslation resource.
 */
export const shopGetProductVariantTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductVariantTranslationJsonld>(
    { url: `/api/v2/shop/product-variant-translation/${id}`, method: "get", signal },
    options,
  );
};

export const getShopGetProductVariantTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/shop/product-variant-translation/${id}`] as const;
};

export const getShopGetProductVariantTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetProductVariantTranslationItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>
  > = ({ signal }) => shopGetProductVariantTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetProductVariantTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>
>;
export type ShopGetProductVariantTranslationItemQueryError = void;

/**
 * @summary Retrieves a ProductVariantTranslation resource.
 */
export const useShopGetProductVariantTranslationItem = <
  TData = Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductVariantTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetProductVariantTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
