/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { ProductAssociationTypeTranslationJsonld } from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductAssociationTypeTranslation resource.
 */
export const adminGetProductAssociationTypeTranslationItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductAssociationTypeTranslationJsonld>(
    { url: `/api/v2/admin/product-association-type-translations/${id}`, method: "get", signal },
    options,
  );
};

export const getAdminGetProductAssociationTypeTranslationItemQueryKey = (id: string) => {
  return [`/api/v2/admin/product-association-type-translations/${id}`] as const;
};

export const getAdminGetProductAssociationTypeTranslationItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminGetProductAssociationTypeTranslationItemQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>
  > = ({ signal }) => adminGetProductAssociationTypeTranslationItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetProductAssociationTypeTranslationItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>
>;
export type AdminGetProductAssociationTypeTranslationItemQueryError = void;

/**
 * @summary Retrieves a ProductAssociationTypeTranslation resource.
 */
export const useAdminGetProductAssociationTypeTranslationItem = <
  TData = Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminGetProductAssociationTypeTranslationItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetProductAssociationTypeTranslationItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
