/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  ApiProductsAttributesGetSubresource200,
  ApiProductsAttributesGetSubresourceParams,
  ProductAttributeValueJsonldShopProductAttributeValueRead,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a ProductAttributeValue resource.
 */
export const shopGetProductAttributeValueItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductAttributeValueJsonldShopProductAttributeValueRead>(
    { url: `/api/v2/shop/product-attribute-values/${id}`, method: "get", signal },
    options,
  );
};

export const getShopGetProductAttributeValueItemQueryKey = (id: string) => {
  return [`/api/v2/shop/product-attribute-values/${id}`] as const;
};

export const getShopGetProductAttributeValueItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetProductAttributeValueItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>> = ({
    signal,
  }) => shopGetProductAttributeValueItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetProductAttributeValueItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>
>;
export type ShopGetProductAttributeValueItemQueryError = void;

/**
 * @summary Retrieves a ProductAttributeValue resource.
 */
export const useShopGetProductAttributeValueItem = <
  TData = Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof shopGetProductAttributeValueItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetProductAttributeValueItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves the collection of ProductAttributeValue resources.
 */
export const apiProductsAttributesGetSubresource = (
  code: string,
  params?: ApiProductsAttributesGetSubresourceParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApiProductsAttributesGetSubresource200>(
    { url: `/api/v2/shop/products/${code}/attributes`, method: "get", params, signal },
    options,
  );
};

export const getApiProductsAttributesGetSubresourceQueryKey = (
  code: string,
  params?: ApiProductsAttributesGetSubresourceParams,
) => {
  return [`/api/v2/shop/products/${code}/attributes`, ...(params ? [params] : [])] as const;
};

export const getApiProductsAttributesGetSubresourceQueryOptions = <
  TData = Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>,
  TError = void,
>(
  code: string,
  params?: ApiProductsAttributesGetSubresourceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiProductsAttributesGetSubresourceQueryKey(code, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>> = ({
    signal,
  }) => apiProductsAttributesGetSubresource(code, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiProductsAttributesGetSubresourceQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>
>;
export type ApiProductsAttributesGetSubresourceQueryError = void;

/**
 * @summary Retrieves the collection of ProductAttributeValue resources.
 */
export const useApiProductsAttributesGetSubresource = <
  TData = Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>,
  TError = void,
>(
  code: string,
  params?: ApiProductsAttributesGetSubresourceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof apiProductsAttributesGetSubresource>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getApiProductsAttributesGetSubresourceQueryOptions(code, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
