/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  OrderItemUnitJsonldAdminOrderItemUnitRead,
  OrderItemUnitJsonldShopOrderItemUnitRead,
} from "../.ts.schemas";
import { customInstance } from "../../mutator/custom-client-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * @summary Retrieves a OrderItemUnit resource.
 */
export const adminGetOrderItemUnitItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OrderItemUnitJsonldAdminOrderItemUnitRead>(
    { url: `/api/v2/admin/order-item-units/${id}`, method: "get", signal },
    options,
  );
};

export const getAdminGetOrderItemUnitItemQueryKey = (id: string) => {
  return [`/api/v2/admin/order-item-units/${id}`] as const;
};

export const getAdminGetOrderItemUnitItemQueryOptions = <
  TData = Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAdminGetOrderItemUnitItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>> = ({
    signal,
  }) => adminGetOrderItemUnitItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AdminGetOrderItemUnitItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>
>;
export type AdminGetOrderItemUnitItemQueryError = void;

/**
 * @summary Retrieves a OrderItemUnit resource.
 */
export const useAdminGetOrderItemUnitItem = <
  TData = Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof adminGetOrderItemUnitItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAdminGetOrderItemUnitItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieves a OrderItemUnit resource.
 */
export const shopGetOrderItemUnitItem = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<OrderItemUnitJsonldShopOrderItemUnitRead>(
    { url: `/api/v2/shop/order-item-units/${id}`, method: "get", signal },
    options,
  );
};

export const getShopGetOrderItemUnitItemQueryKey = (id: string) => {
  return [`/api/v2/shop/order-item-units/${id}`] as const;
};

export const getShopGetOrderItemUnitItemQueryOptions = <
  TData = Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShopGetOrderItemUnitItemQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>> = ({
    signal,
  }) => shopGetOrderItemUnitItem(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ShopGetOrderItemUnitItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>
>;
export type ShopGetOrderItemUnitItemQueryError = void;

/**
 * @summary Retrieves a OrderItemUnit resource.
 */
export const useShopGetOrderItemUnitItem = <
  TData = Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof shopGetOrderItemUnitItem>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getShopGetOrderItemUnitItemQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
